### ISSUE TITLE
s3 stream filling available memory

### ISSUE THREAD

**Issue by gabriel403** [thephpleague/flysystem-aws-s3-v3#101]
As a basic example:

```
$s3Client = new S3Client([
    'credentials' => ['key' => 'S3_KEY', 'secret' => 'S3_SECRET'],
    'region' => 'eu-west-1',
    'version' => 'latest',
]);
$s3Client->registerStreamWrapper(); // do we still need this?
$s3 = new Filesystem(new AwsS3Adapter($s3Client, 'S3_BUCKET', 'S3_PATH'));

 (new Filesystem(new Local($path)))->writeStream($source, $s3->readStream($source));
```
and whilst monitoring `free -m` I see the memory usage going from the free column into the buff/cache column, it's a big file so I was hoping it wouldn't be using memory. I might be misreading the code but it seems as if it reads the entire remote file before streaming. `readStream` calls `readObject` which calls `getObject` on the s3Client, so doesn't seem to stream.

Also if the file already exists it doesn't report a `file already exists` error until it seems to have read the whole thing, which would seem to support my thoughts that it isn't being streamed properly.

**Comment by frankdejonge** [comment]
@gabriel403 the adapter gets the stream from the aws sdk, we don't have controle over how this stream gets filled or when it's handed back to us. From our end this is the most memory usage friendly as we can get.

**Comment by gabriel403** [comment]
@frankdejonge so we call `$s3Client->registerStreamWrapper();` and flysystem calls getObject (actually `$this->s3Client->getCommand('getObject'`) on the s3Client, which actually returns a stream?

**Comment by frankdejonge** [comment]
@gabriel403 you don't have to register the stream wrapper. The getObject command returns a object containing the stream. We detach the stream and return that.

**Comment by gabriel403** [comment]
OK, thank you @frankdejonge :)
