### ISSUE TITLE
Adding league s3 filesystem breaks auto loading

### ISSUE THREAD

**Issue by cdesewell** [thephpleague/flysystem-aws-s3-v3#103]
From: https://stackoverflow.com/questions/44353842/adding-league-s3-filesystem-breaks-auto-loading

After adding the Leauge S3 filesystem adaptor I receive the following auto loading error on my EBS system.

composor.json:
```
  "require": {
    "php": ">=5.5.0",
    "slim/slim": "2.3.2",
    "slim/extras": "dev-develop",
    "twig/twig":  "1.*",
    "directus/migrations": "dev-master",
    "directus/permissions": "0.9.*@dev",
    "directus/database": "~0.1.3",
    "league/flysystem": "^1.0",
    "league/flysystem-aws-s3-v3": "^1.0",
    "swiftmailer/swiftmailer": "^5.4"   },
```
Error:
> Failed opening required '/var/app/current/vendor/composer/../guzzlehttp/psr7/src/functions_include.php' (include_path='/var/app/current/vendor/phpunit/php-token-stream:/var/app/current/vendor/phpunit/phpunit-mock-objects:/var/app/current/vendor/phpunit/php-code-coverage:/var/app/current/vendor/phpunit/phpunit:/var/app/current/vendor/symfony/yaml:.:/usr/share/pear7:/usr/share/php7') in /var/app/current/vendor/composer/autoload_real.php on line 70

**Comment by frankdejonge** [comment]
@cdesewell from what I see this isn't an issue with flysystem, rather an issue with guzzle, which is required by the aws-php-sdk, which is required by us. This issue should be reported at guzzle, not here.

**Comment by cdesewell** [comment]
Ok Thanks
