### ISSUE TITLE
Missing data in function getMetadata

### ISSUE THREAD

**Issue by wangfei800** [thephpleague/flysystem-aws-s3-v3#105]
I am using Laravel storage. I can save extra metadata for s3 storage using:
Storage::disk($disk)->put($fileName, $body, $s3Params
$s3Params is an array with key 'Metadata'. 

But I can not retrieve full metadata using:
Storage::disk($disk)->getMetadata($fileName)

I found the reason is with function: getMetadata, before return, it calls normalizeResponse(), which removes lots of data in the response and only returns standard metadata, customized metadata is removed.

**Comment by frankdejonge** [comment]
This was recently fixed.
