### ISSUE TITLE
How can I set timeout?

### ISSUE THREAD

**Issue by a-jumping425** [thephpleague/flysystem-aws-s3-v3#116]
Hi,

I'd like to increase the timeout as 3600s. Because I have to upload large video file to S3. So I need to increase the time.
I found this part in amazon document.
(http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#timeout)

Would you let me know how can I do it?

Thank you.

**Comment by frankdejonge** [comment]
@a-jumping425 you can add those configurations in the S3 client, which also accepts those http configurations you linked to.

**Comment by a-jumping425** [comment]
I am sorry. I can't make the sense for the code.
Would you show me some sample code for it?
Thank you.
