### ISSUE TITLE
Problem with multipart-upload and content-length

### ISSUE THREAD

**Issue by kallealberg** [thephpleague/flysystem-aws-s3-v3#117]
I get the following error when i try to upload large files to S3.
Smaller files that does not require multipart works fine.

Tho when i remote the 'ContentLength' option (AwsS3Adapter.php upload function) before upload, the multipart upload works fine.

I have tried with different servers and different s3 endpoints (eu-central-1 and eu-west-1) with the same result.

I started getting these errors about a week ago.
Not sure what to make of this :-)
Any clues?

Error: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 2: Error executing "UploadPart" on "https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=2&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-"; AWS HTTP error: Client error: `PUT https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=2&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server w (truncated...)
 RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>D4FBBC6ED5B2ADDC</RequestId><HostId>JqgxslgdNEBoVO27VV88++pbZID3IMOJxkI7eNDPGEFG1cLRL5bzwab3gb4hgfBCMj33YSkFrQM=</HostId></Error>
- Part 3: Error executing "UploadPart" on "https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=3&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-"; AWS HTTP error: Client error: `PUT https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=3&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server w (truncated...)
 RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>BA0FF6BAE0D104EF</RequestId><HostId>M7aZrrJieX2ceZZ708HjzQ65PJaB43ckHAQgxAp/5GfteC+BXYliYD6DE1q+O4u2WK1Mujf4Gss=</HostId></Error>
- Part 1: Error executing "UploadPart" on "https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=1&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-"; AWS HTTP error: Client error: `PUT https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=1&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server w (truncated...)
 RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>B00513569508D224</RequestId><HostId>AY7mfYZop7AF24ZWIOmiQ2YUoOO0IArQ9zMNWymkck93VNUzm/m+j/vdOlIO0IT1Dp2HVgXpIeE=</HostId></Error>
- Part 4: Error executing "UploadPart" on "https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=4&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-"; AWS HTTP error: Client error: `PUT https://xxxx.s3.eu-central-1.amazonaws.com/D.pdf?partNumber=4&uploadId=1fDClNAW1P21lsnYkl3RjnqPG3nj9926JJicbgufX_Vy8wmB5gyJcMgRgmMgJFc.qER6ZlhkSrV_VqmLl1QMtUBzJ0Awh3UTYBVMpeQ7Y4E-` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server w (truncated...)
 RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>CF889DA5E56141E9</RequestId><HostId>nDOKv2aXBRzeKxy+m8tPt5C9STDN+hTnpacpNsVqr/iymTYgfkDqFrpvLEEZqpRyQaagxTMl8cM=</HostId></Error>

#0 [internal function]: Aws\Multipart\AbstractUploadManager->Aws\Multipart\{closure}()
#1 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Coroutine.php(122): Generator->send(NULL)
#2 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Promise\Coroutine->_handleSuccess(NULL)
#3 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, NULL, Array)
#4 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#5 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#6 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\Promise\Promise->wait()
#15 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true)
#16 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#17 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#18 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#19 /Users/kalle/Workspace/xxxx/app/Vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#20 /Users/kalle/Workspace/xxxx/app/Vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(30): GuzzleHttp\Promise\Promise->wait()
#21 /Users/kalle/Workspace/xxxx/app/Vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(587): Aws\S3\S3Client->upload('xxxx', 'D.pdf', Resource id #192, 'public-read', Array)
#22 /Users/kalle/Workspace/xxxx/app/Vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(368): League\Flysystem\AwsS3v3\AwsS3Adapter->upload('D.pdf', Resource id #192, Object(League\Flysystem\Config))
#23 /Users/kalle/Workspace/xxxx/app/Vendor/league/flysystem/src/Filesystem.php(87): League\Flysystem\AwsS3v3\AwsS3Adapter->writeStream('D.pdf', Resource id #192, Object(League\Flysystem\Config))
#24 /Users/kalle/Workspace/xxxx/app/Vendor/league/flysystem/src/MountManager.php(213): League\Flysystem\Filesystem->writeStream('D.pdf', Resource id #192, Object(League\Flysystem\Config))
#25 /Users/kalle/Workspace/xxxx/app/Console/Command/BackboneShell.php(46): League\Flysystem\MountManager->copy('D.pdf', 'D.pdf')
#26 /Users/kalle/Workspace/xxxx/lib/Cake/Console/Shell.php(458): BackboneShell->backup()
#27 /Users/kalle/Workspace/xxxx/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('backup', Array)
#28 /Users/kalle/Workspace/xxxx/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#29 /Users/kalle/Workspace/xxxx/app/Console/cake.php(47): ShellDispatcher::run(Array)
#30 {main}

**Comment by dgpro** [comment]
@kallealberg Could you tell me how did you solve this problem? as I'm facing it as well for just 160Mb files.

**Comment by dgpro** [comment]
Updating composer fixed the issue
```
  - Updating spatie/laravel-backup (4.18.0 => 4.18.1): Downloading (100%)
  - Updating aws/aws-sdk-php (3.31.2 => 3.31.3): Downloading (100%)
```
