### ISSUE TITLE
ServerSideEncryptionCustomerKeys Not Supported?

### ISSUE THREAD

**Issue by michaelcurry** [thephpleague/flysystem-aws-s3-v3#120]
Looking into the `$metaOptions` array (https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L33), there is an ability to use `ServerSideEncryption` and `SSEKMSKeyId`, but not customer keys (http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html).  

The reason we want to use customer keys is so a customer can upload a document and they control the key used to encrypt their files.  It is important some of our customers have the ability to encrypt their files so even we can't decrypt them.

The AWS S3 client does support this functionality, it just looks like FlySystem is not properly passing the data through.  (https://github.com/aws/aws-sdk-php/blob/master/src/S3/SSECMiddleware.php)

Please let me know if i am missing something here 😃

**Comment by michaelcurry** [comment]
Following up on this :+1: 

Has anyone in The PHP League had a chance to look at this issue yet?

**Comment by frankdejonge** [comment]
@michaelcurry if you can figure out the keys that need to be passed along we can account for this, add them to the metaOptions array if needed.

**Comment by michaelcurry** [comment]
Thanks for getting this into the array @kstich :+1:
