### ISSUE TITLE
Out of memory on streams

### ISSUE THREAD

**Issue by sajjadrad** [thephpleague/flysystem-aws-s3-v3#124]
Hello,

I used this code to stream file from s3 via Laravel ([By Frank](https://stackoverflow.com/a/29747052)):

```
<?php

$fs = Storage::disk('diskname')->getDriver();
$stream = $fs->readStream($file);

return Response::stream(function() use($stream) {
    fpassthru($stream);
}, 200, [
    "Content-Type" => $fs->getMimetype($file),
    "Content-Length" => $fs->getSize($file),
    "Content-disposition" => "attachment; filename=\"" . basename($file) . "\"",
]);

```

But sometimes, there is **out of memory** error on `fpassthru` function like this:
`Out of memory (allocated 4194304) (tried to allocate 320540672 bytes)`

Is there anyway to stream file from s3 without RAM limit problem?

**Comment by fideloper** [comment]
I'm going to be making a video out of this solution, but what I do is grab the S3 driver (Client) directly and use some methods from that as shown here: https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-stream-wrapper.html

Here's some code from a project that uses it. An `Export` is just a database record recording the file to be downloaded.

The secret sauce is the call to `$this->client->registerStreamWrapper();` which lets you use PHP native functions to stream files from S3 (it monkey-patches them).

```php
<?php

namespace App\Http\Responses;

use Storage;
use App\Export;

class S3FileStream
{
    /**
     * @var \League\Flysystem\AwsS3v3\AwsS3Adapter
     */
    private $adapter;

    /**
     * @var \Aws\S3\S3Client
     */
    private $client;

    /**
     * @var Export
     */
    private $export;

    /**
     * S3FileStream constructor.
     * @param Export $export
     * @param string $adapter
     */
    public function __construct(Export $export, $adapter='s3')
    {
        $this->export = $export;

        $this->adapter = Storage::disk($adapter)->getAdapter();
        $this->client = $this->adapter->getClient();
    }

    /**
     * Output file to client
     */
    public function output()
    {
        return $this->headers()
            ->stream();
    }

    /**
     * Output headers to client
     * @return $this
     */
    protected function headers()
    {
        $object = $this->client->headObject([
            'Bucket' => $this->adapter->getBucket(),
            'Key' => $this->export->location,
        ]);

        $headers = [
            'Last-Modified' => $object['LastModified'],
            // 'Etag' => $object['ETag'], # We are not currently implementing validation caching
            'Accept-Ranges' => $object['AcceptRanges'],
            'Content-Length' => $object['ContentLength'],
            'Content-Type' => $object['ContentType'],
            'Content-Disposition' => 'attachment; filename=' . $this->export->filename),
        ];

        foreach($headers as $header => $value)
        {
            header("{$header}: $value");
        }

        return $this;
    }

    /**
     * Stream file to client
     * @throws \Exception
     */
    protected function stream()
    {
        $this->client->registerStreamWrapper();

        // Open a stream in read-only mode
        if (!($stream = fopen("s3://{$this->adapter->getBucket()}/{$this->export->location}", 'r'))) {
            throw new \Exception('Could not open stream for reading export ['.$this->export->id.']');
        }

        // Check if the stream has more data to read
        while (!feof($stream)) {
            // Read 1024 bytes from the stream
            echo fread($stream, 1024);
        }
        // Be sure to close the stream resource when you're done with it
        fclose($stream);
    }
}
```

**Comment by frankdejonge** [comment]
The stream we return is actually the same (detached) stream used in the stream wrapper provided by the s3Client. My guess would actually be that the server is just running out of resources, perhaps that can be looked into too. The reason for me thinking in this direction is the word "__sometimes__". When is doesn't always happen on a particular size asset, but it does happen sometimes it can just be that multiple fpm child processes together consume too much memory, causing the error.

**Comment by twistor** [comment]
This isn't fixed by passing `['@http' => ['stream' => true]]`?

**Comment by fideloper** [comment]
Hey that's good to know, I need to re-record a video now 👍

**Comment by frankdejonge** [comment]
@sajjadrad did you see @twistor's comment?

**Comment by sajjadrad** [comment]
@frankdejonge Should I pass it as headers? The problem is, it doesn't happen every time. I close issue and test this code. If it happen again, I will reopen it.

Thanks

**Comment by rovansteen** [comment]
@twistor I'm running in to the same issue, where should I pass the array you mention?

**Comment by McCaulay** [comment]
@sajjadrad @rovansteen Came across the same issue. ```['@http' => ['stream' => true]]``` can be passed as the second argument to the ```getCommand``` function in the S3 Client.

If you're using Laravel like me, then instead you need to add an "options" array to your ```filesystems.php``` config. This is mine for example;

```php
's3' => [
    'driver' => 's3',
    'key' => env('AWS_ACCESS_KEY_ID'),
    'secret' => env('AWS_SECRET_ACCESS_KEY'),
    'region' => env('AWS_DEFAULT_REGION'),
    'bucket' => env('AWS_BUCKET'),
    'url' => env('AWS_URL'),
    'options' => [
        '@http' => [
            'stream' => true,
        ],
    ],
],
```

If you're downloading directly from AWS to the user, you can do something like this;

```php
$filename = 'test/example.txt';
$disk = Storage::disk('s3');

return response()->streamDownload(function () use ($disk, $filename) {
    fpassthru($disk->readStream($filename));
}, basename($filename), [
    'Content-Length' => $disk->getSize($filename),
    'Content-Type' => $disk->getMimetype($filename),
]);
```

**Comment by jasperf** [comment]
@McCaulay Does `putFile` ([docs](https://laravel.com/docs/master/filesystem#storing-files)) using `Storage` facade not do the same thing?

> If you would like Laravel to automatically manage streaming a given file to your storage location, you may use the putFile or putFileAs method. This method accepts either a Illuminate\Http\File or Illuminate\Http\UploadedFile instance and will automatically stream the file to your desired location

Still learning about all this and trying to improve image uploads to Spaces including the usage of streaming, serializing PutObjects, multipart uploads of large files and so on.. And it seems streaming of 5MB up data would be good. Then I found out about `putFile` for the streaming of data.. and bumped into possible ram issues and usage of `fopen`.. and also wound up reading this thread.

**Comment by tstrijdhorst** [comment]
> @twistor I'm running in to the same issue, where should I pass the array you mention?

For anyone still wondering if you are using flysystem directly, you should pass it in the options of the AwsS3Adapter not the S3Client.

```php

new AwsS3Adapter(
				new S3Client(
					[
						'credentials' => [
							'key'    => Config::get('AWS_S3_KEY'),
							'secret' => Config::get('AWS_S3_SECRET'),
						],
						'region'      => Config::get('AWS_S3_REGION'),
						'version'     => Config::get('AWS_API_VERSION'),
					]
				), $bucket, $prefix='',['@http' => ['stream' => true]]
			)
```
