### ISSUE TITLE
IAM Permissions documented?

### ISSUE THREAD

**Issue by fideloper** [thephpleague/flysystem-aws-s3-v3#125]
Hey!

Not sure where a PR is appropriate - are the IAM Permissions used for the S3 adapter documented? (I couldn't find them).

After reviewing the code, here is what I believe is a complete set of method calls made over the AWS API (but I don't use every bit of functionality in production to truly test it):

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1420044805001",
            "Effect": "Allow",
            "Action": [
                "s3:ListObjects",
                "s3:HeadObject",
                "s3:CopyObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:GetObjectAcl",
                "s3:PutObjectAcl",
                "s3:PutObject",
                "s3:CopyObject",
                "s3:UploadPart",
                "s3:CreateMultipartUpload"
            ],
            "Resource": [
                "arn:aws:s3:::your-bucket-name",
                "arn:aws:s3:::your-bucket-name/*"
            ]
        }
    ]
}
```

**Comment by frankdejonge** [comment]
I've added them in the docs! Thanks for sharing this! https://github.com/thephpleague/flysystem/commit/810ff30369779b4b289f2ceb237047db70db78e1

**Comment by frankdejonge** [comment]
They should be viewable here now: http://flysystem.thephpleague.com/adapter/aws-s3-v3/

**Comment by fideloper** [comment]
Beautiful!

**Comment by szepeviktor** [comment]
@frankdejonge Could you please point out which Action is necessary in the bucket itself (not its content) outside `s3:ListBucket`?
Thank you!

We use these minimal permissions with an IAM user only for this bucket.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1473779509001",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKET-NAME"
            ]
        },
        {
            "Sid": "Stmt1473779509000",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKET-NAME/*"
            ]
        }
    ]
}
```

**Comment by fideloper** [comment]
To my knowledge it's just `s3:ListBucket` that's done on the bucket itself (vs the objects within it). 

However if you're getting any errors, let us know the error message you're receiving.

**Comment by szepeviktor** [comment]
@fideloper Thank you for your support.

> File not found at path: 4141/cb1c863f27d2f31818f180cecf860879.jpg {"exception":"[object] (League\\Flysystem\\FileNotFoundException(code: 0): File not found at path: 4141/cb1c863f27d2f31818f180cecf860879.jpg at /home/stager/website/html/vendor/league/flysystem/src/Filesystem.php:388)

We run spatie/laravel-medialibrary in a queue.
I've check `4141/cb1c863f27d2f31818f180cecf860879.jpg` with `s3cmd get` and though HTTPS as our bucket is public.

**Comment by szepeviktor** [comment]
@fideloper As reading my own comment: the queue *remembers* the AWS access key which was recently changed to the above minimal permissions. So it tried the **old** keys!

Excuse me for the noise!
