### ISSUE TITLE
Can't use @http progress option when uploading a file to S3.

### ISSUE THREAD

**Issue by altaraven** [thephpleague/flysystem-aws-s3-v3#126]
Trying to pass this 
```php [
            '@http' => [
                'progress' => function(){
                        ...
                 }
           ]
   ]
```
as 3-rd param to ```\League\Flysystem\AwsS3v3\AwsS3Adapter::upload``` method (actually ```write()``` but doesn't matter). Using Laravel as a wrapper for this, 3-rd param 
```php 
$result = \Storage::disk('s3')->put()
```
Since '@http' doesn't exist in ```$metaOptions``` array and ```\League\Flysystem\AwsS3v3\AwsS3Adapter::getOptionsFromConfig``` doesn't pass this option to S3 Client, I can't use this S3 feature. Please advice what to do.
https://stackoverflow.com/questions/10187653/php-s3-upload-progress

**Comment by slaughter550** [comment]
@frankdejonge or @GrahamCampbell is this desired behavior within this repo? I imagine that either an event listener could be registered or the config could be expanded to support this. If you guys agree that it belongs in this repo I'm happy to make a PR for it!

**Comment by frankdejonge** [comment]
@slaughter550 go for it! Make sure you account for other supported `@http` options and possible merges regarding those options. 👍

**Comment by craigpaul** [comment]
@frankdejonge Would this still be desired within this repo? Ran into a use case where I need this and don't wanna bother rewriting the entire stream abstraction in my application. If so, I'm going to take a stab at it

**Comment by nadirabbas** [comment]
@slaughter550 Did you finally do it?
