### ISSUE TITLE
Support for Digital Ocean Spaces?

### ISSUE THREAD

**Issue by eriktobben** [thephpleague/flysystem-aws-s3-v3#127]
Hi!

Does this library support Spaces from Digital Ocean?
https://www.digitalocean.com/products/object-storage/

**Comment by frankdejonge** [comment]
It should be, they say they have feature/api parity with s3. I've not given it a spin myself because the docs didn't really specify how to go about credentials. But it should be good to go.

**Comment by frankdejonge** [comment]
@eriktobben also: https://www.digitalocean.com/community/questions/the-php-league-flysystem-for-spaces-object-storage

**Comment by frankdejonge** [comment]
Just verified this, it works:

```php
<?php

use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

include __DIR__.'/vendor/autoload.php';

$client = new S3Client([
    'endpoint' => 'https://nyc3.digitaloceanspaces.com',
    'version' => 'latest',
    'credentials' => [
        'key' => 'KEY',
        'secret' => 'SECRET'
    ],
    'region' => 'nyc3',
]);

$adapter = new AwsS3Adapter($client, 'flysystem-test');
$filesystem = new Filesystem($adapter);
print_r($filesystem->listContents());
```

**Comment by eriktobben** [comment]
Thanks :)

**Comment by SimplyCorey** [comment]
One thing that is not working is pre-signed links because they only support v2 signing. Im not sure of a work around at the moment.
