### ISSUE TITLE
Unable to move a directory

### ISSUE THREAD

**Issue by nWidart** [thephpleague/flysystem-aws-s3-v3#128]
Hello,

I'm currently trying to rename a directory. From my understanding, I need to use the `move()` method for this. On local filesystem driver, this is working fine. However, when using s3, I'm getting the following error:

```
"Error executing "GetObjectAcl" on "https://asgard-modules-dev.s3-eu-west-1.amazonaws.com/assets/media/test-s3?acl"; 

AWS HTTP error: Client error: `GET https://asgard-modules-dev.s3-eu-west-1.amazonaws.com/assets/media/test-s3?acl` resulted in a `404 Not Found` response:↵
<?xml version="1.0" encoding="UTF-8"?>↵

<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...)↵ 

NoSuchKey (client): The specified key does not exist. - <?xml version="1.0" encoding="UTF-8"?>↵

<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>assets/media/test-s3</Key><RequestId>B50AF4134D66FA68</RequestId><HostId>yliO7CUIt5PBsix/C339BrdFzrMTsKsommGc0fVOculaITBfC9CDPg2X43oXnW9RjnvRynmi39k=</HostId></Error>"
```
(edit: tried formatting the error to be more readable)

When I dump my `from` and `to` paths, I have the correct path names:

```
"/assets/media/test-s3" (from)
"/assets/media/test-s3333" (to)
```

The from path does exist at that location.

Am I missing something?

Thanks!

**Comment by frankdejonge** [comment]
@nWidart hi, copy doesn't work for "virtual" directories. All in all it's a limitation of S3, they don't support the concept of folder renames. Not in their SDK or in their GUI's.

**Comment by frankdejonge** [comment]
Some more contextual information, even actual directories (which are objects in S3) don't move their "child" objects in S3. So in general the behaviour is a little different. If you want safe cross FS operations, treat it like a key/value store. Then you get everything as expected.

**Comment by frankdejonge** [comment]
Renames work for files, not for directories. So if you disregard the fact "directories exist", in which case you only have files in paths, then you're safe.

**Comment by nWidart** [comment]
Hm ok, I'm not 100% following, but ok. :D

Renames work for files, but not folders, but in s3, there are no folders and just files. 
So why doesn't it work?

- If I want to rename an empty folder, I would need to delete the folder + create a new one with the new name.
- If I want to rename a folder with children, I would need to manually copy/delete each child

I guess I'll hold off of this for now until a better approach is implemented on my end. (planning to now move the files on disk, but only their virtual paths in database, with a front controller)

Thanks for your help!

**Comment by ctf0** [comment]
it seems the only solution for this is

- get all the files in the old dir
- make new dir with new name
- move the files into that new dir
- delete the original one

however not sure how the permissions would work, because atm when trying to move files from dir to another, the permission will reset to the bucket owner, in other words the `everyone` permission will be removed.

@frankdejonge is there a way to set a specific permission to files on upload/move ?

**Comment by frankdejonge** [comment]
Hi @ctf0, moving will preserve permissions.

**Comment by ctf0** [comment]
how about upload, can i set permission automatically for everyone to read the file ? or is this done through the bucket permissions ?

**Comment by frankdejonge** [comment]
You can set default permissions on the bucket.

**Comment by frankdejonge** [comment]
Closing this issue because AWS doesn't allow this.
