### ISSUE TITLE
Mimetype not set on multipart upload

### ISSUE THREAD

**Issue by mnimants** [thephpleague/flysystem-aws-s3-v3#129]
Hi,

I'm trying to upload file to S3 with this code 
` Storage::disk('s3')->getDriver()->put('ebooks/' . $ebook->ebook, $file, [
                'visibility' => 'public',
                'mimetype' => 'application/pdf'
            ]);`

For small pdf's it works good and correct content type is set.  But when I try to upload pdf which size is 94M it starts multipart file upload and then content type always is application/octet-stream. 

Is there any way around this? 

Thanks

**Comment by mnimants** [comment]
It doesn't set "application/pdf" with ContentType passed either if it's that what you mean.

**Comment by kstich** [comment]
Please make sure you're on at least version [3.36.28 of the AWS SDK for PHP](https://github.com/aws/aws-sdk-php/releases/tag/3.36.28), as we fixed a bug where supplied `'ContentTypes'` were being overridden for `MultipartUpload` based operations - which includes large files over `->upload()`. See aws/aws-sdk-php#1397.

**Comment by frankdejonge** [comment]
Closing this since this was a AWS SDK issue.
