### ISSUE TITLE
has() will propagate an S3 exception rather than returning false

### ISSUE THREAD

**Issue by iansltx** [thephpleague/flysystem-aws-s3-v3#13]
has() should catch the metadata 404 exception if the file doesn't exist and return false, rather than letting it propagate.

**Comment by iansltx** [comment]
getMetadata() may also have this same issue, where what should return false instead throws an S3Exception all the way up the stack...leaky abstraction or something like that. The above issue (which will turn into a PR momentarily) doesn't fix the getMetadata() case, just the has() one, but it's easy enough to move the logic if warranted.

**Comment by helmut** [comment]
Yeah for me it threw an exception. I was expecting to get false back.

**Comment by frankdejonge** [comment]
Fixed in 749a4d587dd2d21329324a0bb52c5abb82b2c6d4
