### ISSUE TITLE
Getting Missing required client configuration options: region Error

### ISSUE THREAD

**Issue by Laraveldeep** [thephpleague/flysystem-aws-s3-v3#131]
I am trying to use this package on Laravel 5.5 as per their documentation https://laravel.com/docs/5.5/filesystem#driver-prerequisites

I have all the credentials setup correctly. However when I am trying to store the file on S3, I am getting this error
```
Missing required client configuration options: region: (string) A "region" configuration value is required for the "s3" service (e.g., "us-west-2"). A list of available public regions and endpoints can be found at http://docs.aws.amazon.com/general/latest/gr/rande.html.
```
This is thrown from
```
vendor\aws\aws-sdk-php\src\ClientResolver.php

    private function throwRequired(array $args)
    {
        $missing = [];
        foreach ($this->argDefinitions as $k => $a) {
            if (empty($a['required'])
                || isset($a['default'])
                || isset($args[$k])
            ) {
                continue;
            }
            $missing[] = $this->getArgMessage($k, $args, true);
        }
        $msg = "Missing required client configuration options: \n\n";
        $msg .= implode("\n\n", $missing);
        throw new IAE($msg);
    }
```

I suspect something is not passed properly. Just a guess anyway.

My question on Laracast: https://laracasts.com/discuss/channels/laravel/missing-required-client-configuration-options-region-while-trying-to-implement-s3

Thanks!

**Comment by frankdejonge** [comment]
This is a laravel issue, laravel creates the client, we only use the client.
