### ISSUE TITLE
Thumbnails are saved to local server

### ISSUE THREAD

**Issue by php5developer** [thephpleague/flysystem-aws-s3-v3#132]
Hello,

I'm using Amazon s3 adapter. It is working fine, however the thumbnails are saved on local server. Can someone point me how I can configure adapter to save thumbnails to Amazon s3. 

I also have another questions. The files that were saved to S3 have private permissions. How to make them public?

Thank you.

**Comment by frankdejonge** [comment]
@php5developer Hi, Flysystem doesn't provide thumbnail functionality, are you using a package that uses flysystem maybe? Because it'll probably be a question you should ask there.
