### ISSUE TITLE
AWS HTTP error: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by jonasmorthorst** [thephpleague/flysystem-aws-s3-v3#134]
Hi.

Everything was working perfectly, until a couple of days ago suddenly I can't download or upload files to AWS S3 from my API. I was getting this response:

`"Error executing "ListObjects" on "https://s3.eu-central-1.amazonaws.com/firmamappen-files?prefix=4%2FphpL2VUSE.pdf%2F&max-keys=1&encoding-type=url"; AWS HTTP error: count(): Parameter must be an array or an object that implements Countable"`

**Comment by frankdejonge** [comment]
@jonasmorthorst looks to me like that's a exception that comes from the aws sdk rather than this adapter.

**Comment by jonasmorthorst** [comment]
I figured out that it was PHP 7.2 that causes this. So now i lock it to PHP 7.1.12 and it works 😄 
Thanks anyway @frankdejonge.
