### ISSUE TITLE
Where does the adapter go?

### ISSUE THREAD

**Issue by kcee403** [thephpleague/flysystem-aws-s3-v3#135]
Would help if it was a little more obvious where the adapter goes. Thanks.
<?php
use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

include __DIR__ . '/vendor/autoload.php';

$client = new S3Client([
    'credentials' => [
        'key'    => 'your-key',
        'secret' => 'your-secret'
    ],
    'region' => 'your-region',
    'version' => 'latest|version',
]);

$adapter = new AwsS3Adapter($client, 'your-bucket-name');
$filesystem = new Filesystem($adapter);

**Comment by frankdejonge** [comment]
All the docs but 2 (replication and aws-s3-v3) has the filesystem wrapping in the docs. I've fixed that in the main repository.

**Comment by frankdejonge** [comment]
http://flysystem.thephpleague.com/adapter/aws-s3-v3/
