### ISSUE TITLE
S3 count of "Gets" after "Put"

### ISSUE THREAD

**Issue by cdarken** [thephpleague/flysystem-aws-s3-v3#137]
The S3 admin console shows a number of reads almost equal to the count of the uploaded files. Is there anything that I'm doing wrong or is this unavoidable because of how the s3 sdk or flysystem works?

Sorry if this is not the place to ask, but I didn't find any other forum for this kind of discussions.

**Comment by frankdejonge** [comment]
@cdarken Hi. If you question is if we read the file after we write it then the answer is simple; no we don't. I'm not sure how I can help you further or what's really your question.

**Comment by cdarken** [comment]
Thank you for answering. And for this awesome library. I will investigate this issue on my own.
