### ISSUE TITLE
Cannot rename file with spaces in filename on DO Spaces

### ISSUE THREAD

**Issue by leeuweriq** [thephpleague/flysystem-aws-s3-v3#138]
Flysystem advices to use the AWS s3 plugin for connecting to the Digital Ocean Spaces API. 
All goes well when uploading or deleting files. However when trying to rename a file that contains spaces in the file name (ie: "wp nl subscription whitepaper.pdf"), the DO Spaces API returns a 404 due to the urlencoded path:

`$command = $this->s3Client->getCommand(
            'copyObject',
            [
                'Bucket' => $this->bucket,
                'Key' => $this->applyPathPrefix($newpath),
                'CopySource' => urlencode($this->bucket . '/' . $this->applyPathPrefix($path)),
                'ACL' => $this->getRawVisibility($path) === AdapterInterface::VISIBILITY_PUBLIC
                    ? 'public-read' : 'private',
            ] + $this->options
        );`

The urlencode results in this error:

`Error executing "CopyObject" on "https://jbc.ams3.digitaloceanspaces.com/uploads_customer/55/wp%20nl%20subscription%20whitepaper%201.pdf"; AWS HTTP error: Client error: 'PUT https://jbc.ams3.digitaloceanspaces.com/uploads_customer/55/wp%20nl%20subscription%20whitepaper%201.pdf' resulted in a '404 Not Found' response: (....)`

After removing the urlencode function in the CopySource line, I was able to rename the file successfully. 

Could you perhaps add a config to disable the urlencode on the source path?

**Comment by frankdejonge** [comment]
A PR for this would be welcome.

**Comment by promatik** [comment]
Just a quick update on this issue, it seems this isn't a problem any more. I'm able to rename files with spaces on DO Spaces. But, I'm not able to rename folders on the root of a space. It doesn't matter if it has spaces(characters) or not, files on root can be renamed, folders don't.

> "GetObjectAcl" on `"https://***.digitaloceanspaces.com/test?acl"`; AWS HTTP error: Client error: `GET https://***.digitaloceanspaces.com/test?acl` resulted in a `404 Not Found` response:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NoSuchKey</Code>
<BucketName>***</BucketName>
<RequestId>tx0000000000000a638d7d6-005ec6bd5a-*******-fra1a</RequestId>
<HostId>*******-fra1a-fra1</HostId></Error>`
```

**Comment by emielbeinema** [comment]
Does this issue still arise with the changes proposed in #200 (PR #201)? That change fixed my problems with DO Spaces.

**Comment by promatik** [comment]
@emielbeinema just tested the update, and unfortunately no 😕
I still cannot rename folders.

**Comment by frankdejonge** [comment]
Renaming folder is not supported in S3, no way around it.
