### ISSUE TITLE
"failed to open stream: Too many open files" on a single, large file

### ISSUE THREAD

**Issue by hm122** [thephpleague/flysystem-aws-s3-v3#140]
I'm using the Laravel Storage Implementation to copy files to Amazon S3 with your package "league/flysystem-aws-s3-v3": "~1.0".

`Storage::disk('s3')->putFileAs($destinationPath, new File($filePath), $fileName);`
While this works for files up to 1.2GB, it fails with larger files (1.7GB) with the following error:

```
PHP Fatal error:  Uncaught ErrorException: fopen(php://stderr): failed to open stream: operation failed in vendor/    symfony/console/Output/ConsoleOutput.php:150
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fopen(php://std...', '/    ...', 150, Array)
#1 vendor/symfony/console/Output/ConsoleOutput.php(150): fopen('php://stderr', 'w')
#2 vendor/symfony/console/Output/ConsoleOutput.php(44): Symfony\Component\Console\Output\ConsoleOutput->    openErrorStream()
#3 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101):     Symfony\Component\Console\Output\ConsoleOutput->__construct()
#4 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(87):     Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(RuntimeException))
#5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->hand in vendor/symfony/console/Output/    ConsoleOutput.php on line 150
PHP Fatal error:  Uncaught ErrorException: include(vendor/symfony/debug/Exception/FatalErrorException.php): failed to     open stream: Too many open files in vendor/composer/ClassLoader.php:444
Stack trace:
#0 vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/    ...', '...', 444, Array)
#1 vendor/composer/ClassLoader.php(444): include()
#2 vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(136):     spl_autoload_call('Symfony\\Compone...')
#5 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123):     Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(A in vendor/composer/ClassLoader.php on     line 444
```
The error seems strange, since I'm only uploading one file at a time.

Also to mention:

`Storage::putFileAs($destinationPath, new File($filePath), $fileName);`

This works, even with larger files (local copy without s3).

**Comment by frankdejonge** [comment]
This could be because of multi-part uploading in the SDK. I'm at a conference today, but that might give you a direction to look into.

**Comment by hm122** [comment]
I tried to use the multipart uploading, but I'm receiving the same error. Code follows.

`$disk = Storage::disk('s3');
    $uploader = new MultipartUploader($disk->getDriver()->getAdapter()->getClient(), $completePath, [
        'bucket' => Config::get('filesystems.disks.s3.bucket'),
        'key'    => $destinationPath.'/'.$fileName,
    ]);

    try {
      $result = $uploader->upload();
      $this->info('Done.');
    } catch (MultipartUploadException $e) {
      $this->info($e->getMessage());
    }`

**Comment by frankdejonge** [comment]
Sorry, I meant that the problem is actually the multiplart part. It
tries to open to many streams I suspect.

On Fri, 9 Mar 2018, at 8:59 PM, hm122 wrote:
> I tried to use the multipart uploading, but I'm receiving the same
> error. Code follows.> `$disk = Storage::disk('s3');
>  $uploader = new MultipartUploader($disk->getDriver()->getAdapter()-
>  >getClient(), $completePath, [>  'bucket' => Config::get('filesystems.disks.s3.bucket'),
>  'key'    => $destinationPath.'/'.$fileName,
>  ]);


> try { $result = $uploader->upload(); $this->info('Done.'); } catch
> (MultipartUploadException $e) { $this->info($e->getMessage()); }`
>> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/thephpleague/flysystem-aws-s3-v3/issues/140#issuecomment-371929199

**Comment by hm122** [comment]
Ah, I understand. Is there a possibility to limit the number of streams?

**Comment by hm122** [comment]
Solved by increasing ulimit -n.

**Comment by frankdejonge** [comment]
👍
