### ISSUE TITLE
Generating Pre-Signed URL for a file in S3?

### ISSUE THREAD

**Issue by vroad** [thephpleague/flysystem-aws-s3-v3#145]
I'd like to create a pre-signed url from uploaded images which is valid for short period of time, so that only users with valid access roles can access to the URL.
However, it seems that current implementation only support generating public URLs. 

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L466

[Amazon S3 Pre\-Signed URL — AWS SDK for PHP documentation](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html)

And I've just found that @sistemi-etime 's fork already supports creating pre-signed URLs, so you could just merge it to implement this future.

https://github.com/sistemi-etime/flysystem-aws-s3-v3

**Comment by vroad** [comment]
I failed to find that this pull request is already rejected.

https://github.com/thephpleague/flysystem-aws-s3-v3/pull/143

**Comment by sistemi-etime** [comment]
@vroad I created a plugin for this feature 
https://github.com/sistemi-etime/flysystem-plugin-aws-s3-v3

**Comment by vroad** [comment]
@sistemi-etime I'll check that out, thanks!

**Comment by steinwandnick** [comment]
hey guys, why not integrating this feature into this adapter?

If you'd say ok, i'd volunteer taking care about.

If there are any reasons not to integrate this, what truly could be the case, I'd be also glad which reasons these could be. Honestly, I'm happy to learn.
