### ISSUE TITLE
AWS HTTP error: cURL error 77: error setting certificate verify locations

### ISSUE THREAD

**Issue by shihab-92** [thephpleague/flysystem-aws-s3-v3#147]
i'm having an error when im trying to use laravel to update the s3 bucket with a file .the error is as below:
`Error executing "PutObject" on "https://s3.amazonaws.com/siteuploads.promotionefx.com/f90f89a0-3de9-11e8-8324-e52b3f7d8243.csv"; AWS HTTP error: cURL error 77: error setting certificate verify locations:
CAfile: C:\wamp64\bin\php\php5.6.25extras\ssl\cacert.pem.txt
CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

in my controller i have tried this:
`    public function upload(Request $request)
      {
        $validator = Validator::make(
            [
                'fileToUpload'      => Input::file('fileToUpload'),
                'extension' => strtolower(Input::file('fileToUpload')->getClientOriginalExtension()),
            ],
            [
                'fileToUpload'          => 'required',
                'extension'      => 'required|in:csv',
            ]
        );
        if ($validator->fails()) {
            flash('Your file upload has been failed!!', 'danger');
        } else {
        $mail_count=count(file($request->file('fileToUpload')),FILE_SKIP_EMPTY_LINES)-1;
        $new_filename=Uuid::generate().'.'.$request->file('fileToUpload')->getClientOriginalExtension();
        //$file=$request->file('fileToUpload')->storeAs('upload',$new_filename,'public');
        $file=$request->file('fileToUpload')->storeAs('/',$new_filename,'s3');
         flash('Your file has been uploaded!!', 'success');
        }

        return back();
    }
}`

after trying for 4hrs seems like cant figure out how to solve this issue "AWS HTTP error: cURL error 77: error setting certificate verify locations".

**Comment by frankdejonge** [comment]
Your PHP installation is broken, I don't know how to solve this because I don't use windows but there are many hits on google for your problem. As the error message suggests your CA path is not set.
