### ISSUE TITLE
listObjects needs to be changed to listBucket

### ISSUE THREAD

**Issue by joshmbg** [thephpleague/flysystem-aws-s3-v3#149]
When trying to get a list of files form s3, I get the message `Error executing "ListObjects" ... 403 Forbidden`. I tried to add s3:listObjects as a permission in my iam and s3 settings, and all attempts fail - amazon does not allow listObjects to be added as a permission, although it is still present (presumably for legacy use). It appears that the listObjects permission has been changed to listBucket.

So I opened vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php, and changed line 674 from listObjects to listBucket, and it works perfectly.

I believe amazon has replaced listObjects with listBucket, and so this library needs to be changed to use the new method.

**Comment by frankdejonge** [comment]
Buckets are a level above this abstraction. You'll need to specify the correct grants for your credentials.
