### ISSUE TITLE
Add Etag to $resultMap

### ISSUE THREAD

**Issue by nathancall** [thephpleague/flysystem-aws-s3-v3#153]
I have a use case where I'm comparing the hashes of files after being uploaded to S3, and your package already has the capability to grab that from the S3 metadata. All you need to do is add 'ETag' => 'etag' to the $resultMap array and it works great.

**Comment by frankdejonge** [comment]
A PR for this would be accepted.

**Comment by kstich** [comment]
I think [this already exists in the map?](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L29)

**Comment by nathancall** [comment]
I think you're right. Yesterday I updated the version being pulled into my project and there it was. Thanks!
