### ISSUE TITLE
getaddresInfo error - extra dot in address

### ISSUE THREAD

**Issue by IgorDePaula** [thephpleague/flysystem-aws-s3-v3#154]
I used the 1.0.19 version in laravel, and I received this error: https://mybucket.s3..amazon.com
getaddressinfo() because the address has a extra dot.

**Comment by kstich** [comment]
This means you did not specify a `region` in your client configuration. [You can read more about the AWS SDK for PHP's `region` parameter here.](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#cfg-region)

**Comment by IgorDePaula** [comment]
The error:
![captura de tela de 2018-08-03 17-02-30](https://user-images.githubusercontent.com/2833993/43663229-10164f06-973f-11e8-85c0-08e0fbedc95e.png)

The region
![captura de tela de 2018-08-03 17-03-10](https://user-images.githubusercontent.com/2833993/43663249-27cbdbc0-973f-11e8-8fd1-714fc1acf265.png)

**Comment by kstich** [comment]
While S3 has a Global endpoint, you need to specify the region for your S3Client with the SDK. You can read more in the link above. Your bucket's region should be visible in the S3 interface in the list of buckets as well.

**Comment by IgorDePaula** [comment]
Ok, its works now.
Thank you very much.
