### ISSUE TITLE
Is it possible to remove a path prefix?

### ISSUE THREAD

**Issue by martinbean** [thephpleague/flysystem-aws-s3-v3#156]
I’m using filesystem with Laravel and the AWS (v3) adapter. When configuring disks in Laravel, you can specify both `url` and `root` for the S3 client. I was planning on setting the `url` option to a CloudFront distribution so that files would be uploaded to an S3 bucket, but then accessed via CloudFront URLs.

My files are stored in an **/assets** folder in my S3 bucket and the root of my CloudFront distribution is set to the folder. So a file at **/assets/foo.jpg** would be accessible via https://example.cloudfront.com/foo.jpg (no **/assets** prefix).

Therefore, I need to _remove_ the prefix from URLs, rather than prepend. Sort of the opposite of what the third parameter to the [`AwsS3Adapter`][1] class constructor would do.

Is it possible to “remove” a prefix from paths?

[1]: https://github.com/thephpleague/flysystem-aws-s3-v3/blob/420e8f75dd0a21d53233f29a3a14653dcf937343/src/AwsS3Adapter.php#L83

**Comment by frankdejonge** [comment]
This is outside the scope of Flysystem, you can just use `substr` for this.
