### ISSUE TITLE
Incorrect mime-type for epubs

### ISSUE THREAD

**Issue by th-lange** [thephpleague/flysystem-aws-s3-v3#157]
# Used Version:
```
"name": "league/flysystem-aws-s3-v3",
"version": "1.0.19",
"source": {
    "type": "git",
    "url": "https://github.com/thephpleague/flysystem-aws-s3-v3.git",
    "reference": "f135691ef6761542af301b7c9880f140fb12dc74"
},
```
# Issue
When uploading an epub file, the Content-Type is set to "text/plain"

# Expected
The Content-Type should be set to (?) application/zip. 
That is: `MimeType::detectByFilename($path)` resp. getExtensionToMimeTypeMap() should contain epub.

**Comment by frankdejonge** [comment]
This issue should be moved to the main repository.

**Comment by th-lange** [comment]
Yeah. This is correct. As the issue surfaced with aws-s3. But is related to

League\Flysystem\Util\MimeType

Will create a new issue and close this one
