### ISSUE TITLE
InvalidArgumentException Missing required client configuration options

### ISSUE THREAD

**Issue by OrcunOtacioglu** [thephpleague/flysystem-aws-s3-v3#158]
Code:

```
<?php
    function uploadToCloud(Media $media)
    {
        $client = new S3Client([
            'credentials' => [
                'key'    => 'env('DO_SPACES_KEY')',
                'secret' => 'env('DO_SPACES_SECRET')',
            ],
            'region' => 'ams3',
            'version' => 'latest',
            'endpoint' => 'https://ams3.digitaloceanspaces.com',
            ]);

        $adapter = new AwsS3Adapter($client, env('DO_SPACES_BUCKET'));

        $filesystem = new Filesystem($adapter);
        $filesystem->put($media->path, file_get_contents($media->object), [
            'visibility' => 'public
        ];)
    }
```
ERROR:
```
InvalidArgumentException
Missing required client configuration options: 

region: (string)

A "region" configuration value is required for the "s3" service
(e.g., "us-west-2"). A list of available public regions and 
endpoints can be
found at http://docs.aws.amazon.com/general/latest/gr/rande.html.

```
I couldn't find any solution to this issue. It works perfectly in my local machine but not on the server. (My env files are exactly the same in both environments).

**Comment by frankdejonge** [comment]
Please check if this code is actually deployed, because this doesn't behave differently on a server or local. Your configuration is correct.

**Comment by OrcunOtacioglu** [comment]
Yes, the code is in the production already. I'm also stuck and couldn't find any errors.

**Comment by frankdejonge** [comment]
If both the production code and local is the same and the environment variables are the same then everything should also work the same. I expect that the deployment did not go correctly and this code is not actually in production, or at least not where you are looking for it.

**Comment by frankdejonge** [comment]
Additionally there's not enough information for me to investigate any further, sorry.

**Comment by OrcunOtacioglu** [comment]
Thanks!
