### ISSUE TITLE
Inconsistent result on listContents between cache and adapter

### ISSUE THREAD

**Issue by Jurigag** [thephpleague/flysystem-aws-s3-v3#166]
When using method `League\Flysystem\Cached\CachedAdapter->listContents()` i get inconsistent results depending if we are getting from cache or directly from adapter.

For example let's have a key `campaign_id/1234/media` where we have 4 files `1-4.jpg`

When reading listConents from cache using `League\Flysystem\Cached\Storage\AbstractCache` for path `campaign_id/1234/media` we got those 4 elements, but when reading it from `League\Flysystem\AwsS3v3\AwsS3Adapter` we get also campaign_id/1234/media, campaign_id/1234 and campaign_id paths. Is this intentional?

The issue is actually with `Util::emulateDirectories($normalized);` which for some weird reason adds those directories - not sure why.

**Comment by frankdejonge** [comment]
This is indeed intentional. Listing contents in a non-recursive fashion strips certain elements from the result. The output from the adapter can return more, which we use for caching purposes. It's good to note that you shouldn't ever call methods on an adapter directly, but always through the Filesystem class.

**Comment by frankdejonge** [comment]
Also, this difference is mostly caused by emulating the directories, so you get a directory entry even though AWS doesn't really support directories.

**Comment by Jurigag** [comment]
Well we are calling method `listConents` from adapter like this:

```
   $cachedAdapter = new CachedAdapter(
            new AwsS3Adapter($s3, $this->config->application->s3->bucket),
            new S3\Memcache($memcache, $this->config->cache->memcache->prefix, 300)
        );
```

Are we doing something wrong or what?

Yea exactly, this is after doing Util::emulatingDirectories, i don't need this feature actually there, just want to know amount of objects under certain path.

**Comment by frankdejonge** [comment]
You should always wrap this in a `new Filesystem($adapter)` instance. So yes, you're not doing it correctly. This is also documented here: https://flysystem.thephpleague.com/docs/usage/setup/

**Comment by Jurigag** [comment]
Well indeed you are right, calling it from Filesystem works. Sorry for wasting your time, not sur why we don't use it.

**Comment by frankdejonge** [comment]
👍 no problem. If your company uses Flysystem commercially please consider sponsorring its development: https://www.patreon.com/frankdejonge
