### ISSUE TITLE
ContentType is always text/plain

### ISSUE THREAD

**Issue by challgren** [thephpleague/flysystem-aws-s3-v3#167]
The ContentType for files uploaded is always `text/plain` and this is due to a bug on https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L584 where `Util::guessMimeType($path, $body)` is called however it is expected that `$body` is a string for https://github.com/thephpleague/flysystem/blob/master/src/Util/MimeType.php#L182 to work correctly based on the file contents.

**Comment by frankdejonge** [comment]
Hi, what is the extension of the file you're trying to write?

**Comment by challgren** [comment]
In my use case I'm calling $adapter->write() with the tmp_name as the file path so the extension is not used/supplied by PHP form uploads. I'm using https://github.com/FriendsOfCake/cakephp-upload

**Comment by frankdejonge** [comment]
Ok, then you have more options. You can supply the content type yourself (using finfo's `->file` method) or supply the contents as a string. BTW you should always use a Filesystem class to write, you should never access the adapter directly.

**Comment by challgren** [comment]
Its is using Filesystem Class https://github.com/FriendsOfCake/cakephp-upload/blob/master/src/File/Writer/DefaultWriter.php#L112 

Yeah I think I might have to override the DefaultWriter in FriendsOfCake/cakephp-upload to manually specify the ContentType.

**Comment by frankdejonge** [comment]
Or submit a PR to always include it. If this is common for that uploader then more people experience your issue.

**Comment by challgren** [comment]
I'm going to close this as I think it's really related to the Uploader by not allowing access to set Config during write/writeStream operations.
