### ISSUE TITLE
Read files that are inside a folder without a name

### ISSUE THREAD

**Issue by ManuDoni** [thephpleague/flysystem-aws-s3-v3#169]
Hello,
I can't read a file with a path like this: `folder//sub_sub_folder/file.txt`.
Neither the `has` method nor the `read` can read this file but on the S3 management console I can create these files.
I know the best thing to do is to avoid path like that but I can't because I don't have control over these auto-generated files (they weren't created by me).

How can I read these files?

Thanks in advance

**Comment by frankdejonge** [comment]
Hi, could it be that you're using the adapter directly? It should always be wrapped in a filesystem class which deals with this issue.

**Comment by ManuDoni** [comment]
I'm using the `Storage` facade of laravel with `s3` driver

**Comment by frankdejonge** [comment]
In this case I recommend using the SDK directly, we can't facilitate this.

**Comment by ManuDoni** [comment]
Thanks, I'll try

**Comment by ManuDoni** [comment]
I was wrong, the `has` and `read` methods work if I use them directly from the flysystem adapter.
If I use `exists` and `get` methods from the laravel class `Illuminate\Filesystem\FilesystemAdapter` i get `false` and a `Illuminate/Contracts/Filesystem/FileNotFoundException` exception respectively

**Comment by ManuDoni** [comment]
I opened an issue here: https://github.com/laravel/framework/issues/28255

**Comment by ManuDoni** [comment]
I found the problem in `League\Flysystem\Util::normalizeRelativePath`, used in most of the methods of `League\Flysystem\Filesystem`. This function breaks these weird paths.

**Comment by frankdejonge** [comment]
Hi, that feature is a requirement to ensure cross-filesystem portability. Flysystem is an 80-20 solution. It covers 80% of the use-cases, but will never cover 100% (because of mutuality-exclusive behaviour like this). I again recommend you to just use the SDK of AWS for this.

**Comment by ManuDoni** [comment]
Ok, thank you. I will use AWS SDK directly.

**Comment by frankdejonge** [comment]
Thank you for understanding 👍
