### ISSUE TITLE
How do I add x-amz-security-token to request?

### ISSUE THREAD

**Issue by adamtester** [thephpleague/flysystem-aws-s3-v3#175]
I am migrating to AWS Lambda and whereas my code worked before, now the IAM keys are generated with a short lifetime from the role of the lambda function. 

The docs say I need to add `x-amz-security-token` to the request
https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#UsingTemporarySecurityCredentials

Is there a way to handle this? AWS injects the `AWS_SESSION_TOKEN` variable automatically.

**Comment by frankdejonge** [comment]
Hi @adamtester. You should raise this issue with the AWS SDK repository. We simply consume that library here.

**Comment by adamtester** [comment]
@frankdejonge ok thanks, I'll report back to this issue when I figure it out!

**Comment by jdavidbakr** [comment]
@adamtester - did you ever solve this?  I'm trying to do the same thing and am struggling to figure out how.
