### ISSUE TITLE
Incomplete stream body?

### ISSUE THREAD

**Issue by mindplay-dk** [thephpleague/flysystem-aws-s3-v3#178]
We've run into a problem where image streams apparently are sometimes interrupted, and we end up with images looking like this:

![image](https://user-images.githubusercontent.com/103348/62619239-8f883c00-b916-11e9-9d3f-725535857aab.png)

Apparently, ImageMagick isn't picky about reading half a JPEG file, and we end up with random/scrambled pixels - which then gets resized and cached.

This happens at random, and clearing the cached image fixes it - so, attempting to read the same stream again, it's usually always a success after retrying.

There could be any number of reasons why the stream gets interrupted, since networks are unreliable by definition - but I would expect the S3 client would throw an exception if the stream ends before reaching `Content-Length`? Maybe it doesn't? I did a quick search and didn't find any relevant referenced to `Content-Length` in the client's code. (I don't know much about S3 services myself - all I did was plug in the adapter and configure the credentials.)

Is there some way we can validate the length of the stream against `Content-Length` in the adapter? (should we?)

Is there some way I can validate it on our end? (should I need to? networks are unreliable by definition, so this sort of problem can occur even on a stable network if something gets rebooted, etc. - in that case, I'd expect an exception from *one* of these layers, since caching on our end will cause these problems to persist and frequently requires manual recovery. We have millions of images being served at dozens of resolutions and croppings, etc.)

**Comment by frankdejonge** [comment]
I don't think this is really a Flysystem responsibility TBH. If anything it should probably be a Guzzle thing since they control the transport layer.

**Comment by mindplay-dk** [comment]
Okay, so I'm drilling through the S3 client and Guzzle code... what do you make of this?

```
        $remaining = $maxLen;
        while ($remaining > 0 && !$source->eof()) {
            $buf = $source->read(min($bufferSize, $remaining));
            $len = strlen($buf);
            if (!$len) {
                break;
            }
            $remaining -= $len;
            $dest->write($buf);
        }
```
https://github.com/guzzle/psr7/blob/master/src/functions.php#L387-L396

I'm wondering about the `if (!$len)` clause, which will `break` if no bytes were read.

I suspect that `fread()` could return a zero-byte string under certain conditions - in particular, if the stream in question is non-blocking, I believe it might return 0 bytes, which is not an error... as opposed to `fread()` returning `false`, which indicates an error, but the `!` operator would evaluate to `true` since either `false` or `0` would cast to boolean `false`. So might it actually stop reading just because the network is lagging or something?

A comment on the [manual page](https://www.php.net/manual/en/function.fread.php) says:

> Note that fread() will return '' (empty string) when a timeout occurs unlike socket_read() which returns false

I gather from this comment that reading from a stream with `fread()` is not the same as reading from a socket with `socket_read()` - that is, `fread()`, which works on all types of streams, might not treat a network timeout as an *error* and might just return an empty string instead?

Also, t's supposed to read up to a "maximum" number of bytes, which is provided by a call here:

```
        Psr7\copy_to_stream(
            $source,
            $sink,
            (strlen($contentLength) > 0 && (int) $contentLength > 0) ? (int) $contentLength : -1
        );
```
https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L210-L214

But there is no validation - and this value comes from the `Content-Length` header, so, while `copy_to_stream()` defines it's parameter as a "maximum", the value provided at the call site isn't just a maximum, it's the *expected* number of bytes; having read *fewer* bytes when reaching `eof()` really should be considered an *error*.

What do you think? Should we pass this along to team Guzzle?

**Comment by frankdejonge** [comment]
I would indeed suggest passing this along. If anything, from Flysystem's perspective we can't do anything about it on a transport-level and we won't be responsible for validating the correctness of the transported data afterward either. From this lib's perspective, it should be transparent.
