### ISSUE TITLE
Timeout on AWS lambda

### ISSUE THREAD

**Issue by D4rkMindz** [thephpleague/flysystem-aws-s3-v3#179]
Hi there
First of all, thank you for a great package.
Now to my problem.
If i use the adapter to connect from local to my AWS S3 it works perfectly fine (same config as on the server).
On the other hand, if i use the same code on the server, it will get a timeout from my Lambda function.
I know, this might not be related to flysystem, but i'm desperate.
Here's some code:
```php
/**
 * Get a Flysystem Filesystem instance that is connected to aws
 * @return Filesystem
 */
function aws(): Filesystem
{
    $map = [
        'key' => 'APP_S3_KEY',
        'secret' => 'APP_S3_SECRET',
        'region' => 'APP_S3_REGION',
        'version' => 'APP_S3_VERSION',
        'bucket' => 'APP_S3_BUCKET',
    ];

    $s3 = [];
    // The key's are within this file (yes, it exists on prod 
    $data = json_decode(file_get_contents(__DIR__ . '/../secrets.json'), true)['vars'];
    // parse the keys
    foreach ($map as $key => $env) {
        $s3[$key] = $data[$env];
        if (empty($s3[$key])) {
            throw new InvalidArgumentException("ENV '{$env}' not found. Please set '{$env}' ({$env}=<your-config> in secrets.json) to proceed");
        }
    }

    // This is the interesting part.
    $client = new S3Client([
        'credentials' => [
            'key' => $s3['key'],
            'secret' => $s3['secret'],
        ],
        'region' => $s3['region'],
        'version' => $s3['version'],
    ]);

    $configAdapter = new AwsS3Adapter($client, $s3['bucket']);

    $filesystem = new Filesystem($configAdapter);

    return $filesystem;
}

// works locally but not on AWS
aws()->has('config');
```

Any help is greatly appreciated.

**Comment by frankdejonge** [comment]
Hi @D4rkMindz, I'm sorry but I really do not have a clue. I hope this was somehow a network thing or something, but I wouldn't be able to tell from this. If you have more information feel free to comment and we can re-open the issue.

**Comment by noglitchyo** [comment]
I ran into the exact same issue today. So just for future reference if you get this timeout on Lambda but not locally, most likely it means that you did not create an endpoint to access your resources within your VPC. Just create it as described [here](https://aws.amazon.com/es/blogs/aws/new-vpc-endpoint-for-amazon-s3/) and it will work.
