### ISSUE TITLE
listContents with recursive not returning files in sub directories (duplicating directory string)

### ISSUE THREAD

**Issue by denitsa-cm** [thephpleague/flysystem-aws-s3-v3#180]
Using version 1.0.23 of this package.

**Issue:**

I have an s3 bucket with this structure:

```
Folder 1
  - Folder 2
    - File 1
  - Folder 3
    - File 2
```

And I want to get all the files recursively.

I'm using the `laravel-backup` package (https://github.com/spatie/laravel-backup), which internally calls the `listContents`  with `recursive = true` on the `AwsS3Adapter` via the `allFiles` call on `vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php`.

This line here inside `listContents`:

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L269

causes my directory string to be repeated. 

So if `$directory` enters as `Folder 1`, after the code line linked above, `$prefix` becomes `Folder 1/Folder 1/`. And then the `$listing` is just empty. 

```
[]
```

If I just remove the line that sets the prefix, I do get my listing:

```
array:2 [
  0 => array:6 [
    "Key" => "Folder 1/Folder 2/File 1.zip"
    "LastModified" => Aws\Api\DateTimeResult @1570002413^ {#1984
      date: 2019-10-02 07:46:53.0 +00:00
    }
    "ETag" => ""...""
    "Size" => "18330"
    "StorageClass" => "STANDARD"
    "Owner" => array:1 [
      "ID" => "..."
    ]
  ]
  1 => array:6 [
    "Key" => "Folder 1/Folder 3/File 2.zip"
    "LastModified" => Aws\Api\DateTimeResult @1570002410^ {#1987
      date: 2019-10-02 07:46:50.0 +00:00
    }
    "ETag" => ""...""
    "Size" => "435238"
    "StorageClass" => "STANDARD"
    "Owner" => array:1 [
      "ID" => "..."
    ]
  ]
]
```

I am not sure how to go about this. Could I ask you for some help? :)

**Comment by frankdejonge** [comment]
Hi @denitsa-cm,

I've tried to recreate your situation but am I'm not getting the same results. I've done the following:

```php
$filesystem->put('Folder 1/Folder 2/File 1.txt', 'contents');
$filesystem->put('Folder 1/Folder 3/File 2.txt', 'contents');
var_dump($filesystem->listContents('/', true));
```

For me this returns all the expected information.

Can you share a script that reproduces your case?

**Comment by denitsa-cm** [comment]
Hi @frankdejonge. The problem must be coming from somewhere else, because this actually works for me.

```
    /** @test */
    public function s3FilesystemCanListAllContentsInFolderRecursively()
    {
        $s3Client = new S3Client([
            "driver" => "s3",
            "key" => "my key",
            "secret" => "my secret",
            "region" => "eu-central-1",
            "bucket" => "my bucket",
            "root" => "",
            "version" => "latest",
            "credentials" => ["key" => "my key", "secret" => "my secret"]
        ]);

        $adapter = new AwsS3Adapter($s3Client, 'my bucket');

        $filesystem = new Filesystem($adapter);

        $filesystem->put('Folder 1/Folder 2/File 1.txt', 'contents');
        $filesystem->put('Folder 1/Folder 3/File 2.txt', 'contents');

        dump($filesystem->listContents('Folder 1', true));
    }
```
I am closing this one. Thanks for looking into it!

**Comment by frankdejonge** [comment]
Thanks for coming back and closing the issue 👍

**Comment by lbcd** [comment]
Hello,

I got the same issue. I can write directory and files : 

```
        $this->caFilesystem->createDirectory('AAA');
        $this->caFilesystem->createDirectory('BBB');
        $this->caFilesystem->write('AAA/testA.txt', 'GRRRRRR');
        $this->caFilesystem->write('BBB/testB.txt', 'GRRRRRR');
```

But I can't use `listContents` that just return nothing

```
        $files = $this->caFilesystem->listContents('/', true);

        foreach ($files as $file) {
            dump($file);
        }
```

But `dump($this->caFilesystem->read('/'));` give me what I want in XML.

Here is all code and result page : 
```
<?php

namespace App\Controller\EspaceClient;

use League\Flysystem\Filesystem;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\Translation\t;

class CaFileController extends AbstractController
{
    public function __construct(private Filesystem $caFilesystem)
    {
    }

    /**
     * @Route("/espace-client/ca-files", name="main_app")
     */
    public function caFiles(): Response
    {

        dump(New \DateTime());
        $this->caFilesystem->createDirectory('AAA');
        $this->caFilesystem->createDirectory('BBB');
        $this->caFilesystem->write('AAA/testA.txt', 'GRRRRRR');
        $this->caFilesystem->write('BBB/testB.txt', 'GRRRRRR');


        dump($this->caFilesystem->read('/'));

        $files = $this->caFilesystem->listContents('/', true);

        foreach ($files as $file) {
            dump($file);
        }
        dump('End');
        die();
    }
}
```

![image](https://github.com/thephpleague/flysystem-aws-s3-v3/assets/1815136/347b3a7e-7f27-41bf-927b-7c3a8b658011)

And a minio console captures : 
![image](https://github.com/thephpleague/flysystem-aws-s3-v3/assets/1815136/014dac0b-6b84-4c78-b7a7-db01360a48cf)
![image](https://github.com/thephpleague/flysystem-aws-s3-v3/assets/1815136/74b6eede-78d8-433b-8bdc-80229909245c)
