### ISSUE TITLE
Issue connecting to AWS-compatible service, like Wasabi

### ISSUE THREAD

**Issue by edalzell** [thephpleague/flysystem-aws-s3-v3#182]
Apologies if this is not an appropriate issue, I'm new to the fly system ecosystem.

I'm trying to use Wasabi as my S3 provider (in Laravel), but it does NOT use the `AWS_URL` data:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/6069653/66850002-c9844880-ef2c-11e9-84ca-f1181d2ae3fd.png">

Is this an issue with this adapter? A Flysystem issue ? Or is this a Laravel thing?

Thanks

**Comment by spielfigur** [comment]
Hey there,
you should update your config/filesystems.php like this:
`
's3' => [
            ...
            'endpoint' => env('AWS_URL'),
        ],
`
Just change 'url' to 'endpoint' and it should work.

**Comment by mattlibera** [comment]
this helped me with Linode Object Storage buckets as well. thanks!
