### ISSUE TITLE
Problem with "+" in directory name for DO Spaces

### ISSUE THREAD

**Issue by Doomkyn** [thephpleague/flysystem-aws-s3-v3#184]
Hello,

Making various tests, I found an issue regarding folders having plus (+) in the name.
The problem was that the adapter couldn't list directories inside a directory which name includes the character.
The problem occurs only when the recursive mode is disabled.
Checking the code of the `listContents()` method in the `AwsS3Adapter.php` file, I found out that commenting this condition will make it work as expected
```php
if ($recursive === false) {
    $options['Delimiter'] = '/';
}
```

Not sure if I should make a PR since I have no way to test it in other environments.

**Comment by promatik** [comment]
Hi @Doomkyn do you still have this problem?
I just tested creating a couple of folders and files with plus `+` in their names, and everything was working.

**Comment by frankdejonge** [comment]
Sounds pretty probable that this was a DO issue in their implementation. Closing this, can be re-opened when there is more information.
