### ISSUE TITLE
delete() may return false on success

### ISSUE THREAD

**Issue by halaei** [thephpleague/flysystem-aws-s3-v3#185]
When a delete operation is successful, there is a chance that the s3 object is still available, maybe for a few milliseconds. Therefore calling `has($path)` immediately after delete return true. So this code can return false even on success:
```php
    public function delete($path)
    {
        $location = $this->applyPathPrefix($path);

        $command = $this->s3Client->getCommand(
            'deleteObject',
            [
                'Bucket' => $this->bucket,
                'Key'    => $location,
            ]
        );

        $this->s3Client->execute($command);

        return ! $this->has($path); // File is deleted but possibly still available.
    }
```

**Comment by halaei** [comment]
My assumption was that when I am sure the file really exists then I call delete() and it returns false, it means that s3 failed to delete and I must retry.

**Comment by frankdejonge** [comment]
This is unfortunately not solvable, in V2 this is already solved since there is no has call before a delete. Closing this because it's a breaking change and that's already covered in V2.
