### ISSUE TITLE
Unable to Copy (or Rename) files >5GB.

### ISSUE THREAD

**Issue by MichMich** [thephpleague/flysystem-aws-s3-v3#186]
The S3 API only allows uploads up until 5GB. For larger file (up until 5TB), a multipart upload should be used. The same is try for copying files. 

For more info, see:
https://docs.amazonaws.cn/zh_cn/aws-sdk-php/guide/latest/service/s3-multipart-upload.html (scroll to bottom)

Is there a way to implement this in FlySystem?

**Comment by frankdejonge** [comment]
Hi @MichMich, the AWS SDK does this under the hood itself, it has a threshold to switch to multi-part.

**Comment by MichMich** [comment]
Sorry for the super slow response ... (I ran into the same issue again), but this seems to still be an issue: 
```
Storage::copy('path/to/small/file', 'desitination/for/small/file'); // works
```
But when dealing with large files (>5GB) the following returns false, and doesnt copy the file:
```
Storage::copy('path/to/large/file', 'desitination/for/large/file'); // returns false, file wont be copied.
```
Is this expected behaviour?

**Comment by frankdejonge** [comment]
@MichMich do you know which operation fails? Reading or writing?

**Comment by MichMich** [comment]
The [`copy()` ](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L416)method of AWS doesn't seem to be using read or write. It uses a S3 command. When I check the exception catched at [line 431](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/af7384a12f7cd7d08183390d930c9d0ec629c990/src/AwsS3Adapter.php#L431) the message is:

> The specified copy source is larger than the maximum allowable size for a copy source: 5368709120

**Comment by MichMich** [comment]
It seems AWS has a special function to handle large file copy:
https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/php/example_code/s3/MultipartCopy.php

it might be worth mentioning this in the docs, or implement this copy method for larger files.

**Comment by frankdejonge** [comment]
Another case of abstraction leak, what's not to love ;-)

**Comment by MichMich** [comment]
I just tried to use the "MultiCopy" method on a small file (<5MB, which isn't multipart), and that works. The current copy implementation could be replaced with the MultipartCopy implementation which should fix the issue and won't be a breaking change.

**Comment by sergiuionescu** [comment]
@MichMich how did you resolve this? I think i am running into a similar issue, but i see the latest version on flysystem is not patched.

**Comment by MichMich** [comment]
I just created a method which copies the file for me. So I don't use the Storage impelentation:
```php
use Aws\S3\MultipartCopy;

function copy($sourcePath, $targetPath) {
       $s3Adapter = Storage::disk('s3')->getDriver()->getAdapter();
       $source = '/' . $s3Adapter->getBucket() . '/' . $sourcePath;
       $target = [
              'bucket' => $s3Adapter->getBucket(), 
              'key' => $targetPath
       ];

        $copier = new MultipartCopy($s3Adapter->getClient(), $source, $target);
        $result = $copier->copy();
}
```

If you want to move the file, just copy it to the new location and then delete the source file. 

Please note that the code above is a subset of my implementation. I might have messed things up during this copy/paste, but you probably get what you are looking for ...

**Comment by sergiuionescu** [comment]
Thanks @MichMich !

**Comment by unusorin** [comment]
Amazing implementation. To rename a file you have to multipart copy it and then delete the old one :face_with_head_bandage:

**Comment by frankdejonge** [comment]
Ok, so I dug into this. It was a little hard to track down at first, but the copying through a command is the only place where the implementation does _not_ switch to MultipartCopy when the file is bigger than the normal threshold 😅 I've altered the implementation, and version 1.0.29 of this adapter is tagged which fixed this.

**Comment by MichMich** [comment]
Thanks Frank!
