### ISSUE TITLE
AWSv3 stable is out

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/flysystem-aws-s3-v3#19]
http://blogs.aws.amazon.com/php/post/Tx29HZZVCASVU21/Version-3-of-the-AWS-SDK-for-PHP

**Comment by hannesvdvreken** [comment]
https://github.com/aws/aws-sdk-php/releases/tag/3.0.0

**Comment by frankdejonge** [comment]
@shadowhand a stable release is very close to hit the streets.

**Comment by jeremeamia** [comment]
The `it_should_rethrow_non_404_responses_when_fetching_metadata` spec is failing (not sure why), but other than that, it looks like my pass through the code a few weeks back covered the required changes.

**Comment by GrahamCampbell** [comment]
> a stable release is very close to hit the streets.

Yey. This is a blocker for L5.1.

**Comment by frankdejonge** [comment]
I've just pushed a commit that fixed the broken build.

**Comment by GrahamCampbell** [comment]
BTW, what will the version number be of this release? The branch alias is still `1.0-dev`?

**Comment by frankdejonge** [comment]
@GrahamCampbell it'll be the 1.0.1, the 1.0.0 was already released for the beta, which was broken, so there's not point in upping anything since it was all pretty broken from the start.

**Comment by GrahamCampbell** [comment]
k :)

**Comment by frankdejonge** [comment]
@jeremeamia @shadowhand @GrahamCampbell If I'm not mistaken, we're good to tag `1.0.1` which marks the first stable release on the first stable release of the 3rd major version of the aws php sdk. (Couldn't fit more "on/off the" in there, I tried.)

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by shadowhand** [comment]
:tada:
