### ISSUE TITLE
"it was not seekable" error occurs in putStream

### ISSUE THREAD

**Issue by tai-sho** [thephpleague/flysystem-aws-s3-v3#192]
The upload by the stream is implemented by putStream.
The file to be uploaded exists on Docker, and during development it is around a few kilobytes.
```php
$xml->getFile()->open('r+');  // same to fopen
$resource = $xml->getFile()->handle; // return resource of file
$success = $filesystem->putStream('/remote/file/path', $resource);
```
However, the following error occurred.
```
Exception: A sha256 checksum could not be calculated for the provided upload body, because it was not seekable. 
To prevent this error you can either 
1) include the ContentMD5 or ContentSHA256 parameters with your request, 
2) use a seekable stream for the body, or 
3) wrap the non-seekable stream in a GuzzleHttp\Psr7\CachingStream object. 

You should be careful though and remember that the CachingStream utilizes PHP temp streams. This means that the stream will be temporarily stored on the local disk. in [/app/vendor/aws/aws-sdk-php/src/Signature/SignatureV4.php, line 227]
```

There is a description that it is seekable when debugging, but I don't understand why "because it was not seekable."
```
stream_get_meta_data($resource);
[
        'timed_out' => false,
        'blocked' => true,
        'eof' => false,
        'wrapper_type' => 'plainfile',
        'stream_type' => 'STDIO',
        'mode' => 'a',
        'unread_bytes' => (int) 0,
        'seekable' => true,
        'uri' => '/path/to/hoge.xml'
]

```
Is there anything that seems to be the cause?
Please let me know if you have little information.

php: 7.3
flysystem-aws-s3-v3: 1.0.23

**Comment by frankdejonge** [comment]
Your stream needs to be seekable, what is the $xml->getFile()? It seems to be incompatible with Guzzle, which also makes it that I can't fix it in Flysystem.

**Comment by tai-sho** [comment]
@frankdejonge 
Thanks for the reply.

`$xml->getFile()->handle` is the framework code.
I understand that the second argument of putStream takes a resource type.
 Certainly not compatible with Guzzle, but `$xml->getFile()->handle` is a resource type. The above code is an implementation that opens the local xml with fopen and passes its resource type.

Which class is appropriate for uploading local files using Guzzle?
I tried GuzzleHttp\Psr7\Stream,  but could not pass a value to putStream because Stream is not a resource type.
Or is it wrong to upload a local file with putStream?

**Comment by frankdejonge** [comment]
You should only pass it local file handles, some resources are of different types. So first flush to disk and then use fopen to fetch it.
