### ISSUE TITLE
Large files can't be uploaded to GCS

### ISSUE THREAD

**Issue by raulsh** [thephpleague/flysystem-aws-s3-v3#193]
I'm using this library for Google Cloud Storage S3 API. Small files (under 20 megabytes) upload without problems, but the other files can't be uploaded.

I found a solution for this problem: https://github.com/nextcloud/server/issues/14074

**Comment by frankdejonge** [comment]
This is either a bug in GCS S3 or in the AWS SDK, not a flysystem issue. We use the method that automatically uses the streaming and multi-part options.
