### ISSUE TITLE
Receiving 404 error when doesDirectoryExist() is called via has()

### ISSUE THREAD

**Issue by atrauzzi** [thephpleague/flysystem-aws-s3-v3#198]
I'm running into a situation right now where an `S3Exception` (404) is leaking through `AwsS3Adapter` when checking for a path *and* file that do not exist yet in my bucket.

I'm using the S3 adapter against a local instance of minio which aims to be S3 compatible.  So, if for any reason this error can be directly attributed to that, do mention it so I can raise the inconsistency with them.

```
Error executing "ListObjects" on "http://minio.myproject.mylocal/myproject-regional?prefix=some_path%2fsomething.pdf%2F&max-keys=1&encoding-type=url"; AWS HTTP error: Client error: `GET http://minio.myproject.mylocal/myproject-regional?prefix=some_path%2fsomething.pdf%2F&max-keys=1&encoding-type=url` resulted in a `404 Not Found`
```

**Comment by atrauzzi** [comment]
Nevermind, PEBKAC!  My apologies.

**Comment by frankdejonge** [comment]
👍 thanks for coming back and closing the issue

**Comment by yucomds** [comment]
> I'm running into a situation right now where an `S3Exception` (404) is leaking through `AwsS3Adapter` when checking for a path _and_ file that do not exist yet in my bucket.
> 
> I'm using the S3 adapter against a local instance of minio which aims to be S3 compatible. So, if for any reason this error can be directly attributed to that, do mention it so I can raise the inconsistency with them.
> 
> ```
> Error executing "ListObjects" on "http://minio.myproject.mylocal/myproject-regional?prefix=some_path%2fsomething.pdf%2F&max-keys=1&encoding-type=url"; AWS HTTP error: Client error: `GET http://minio.myproject.mylocal/myproject-regional?prefix=some_path%2fsomething.pdf%2F&max-keys=1&encoding-type=url` resulted in a `404 Not Found`
> ```

Ho you solve this issue .. I'm facing the same problem ...
