### ISSUE TITLE
[V2] Not able to list contents on the root directory 

### ISSUE THREAD

**Issue by scuben** [thephpleague/flysystem-aws-s3-v3#203]
I tried

```php
$flysystem->listContents('', Filesystem::LIST_DEEP)->toArray();
$flysystem->listContents('/', Filesystem::LIST_DEEP)->toArray();
```

but both return zero items. I tracked it down to https://github.com/thephpleague/flysystem-aws-s3-v3/blob/2.x/AwsS3V3Filesystem.php#L307 adding the `/` as a Prefix.

**Comment by frankdejonge** [comment]
Thanks for testing out the Alpha! I've fixed this on master, will tag a new beta soon. 👍
