### ISSUE TITLE
doesDirectoryExist() AwsS3Adapter throws exception on 404

### ISSUE THREAD

**Issue by kickthemooon** [thephpleague/flysystem-aws-s3-v3#204]
I am not sure if this is by design but ...
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L720
throws an exception if status code is 404 `The specified key does not exist`

Does it make sense to catch this as 403 is caught and return false instead of exception?

aws/aws-sdk-php is 3.143.0

**Comment by frankdejonge** [comment]
This looks like an error, I'll check it out.
