### ISSUE TITLE
Exponential Backoff

### ISSUE THREAD

**Issue by jasperf** [thephpleague/flysystem-aws-s3-v3#205]
Does the S3 driver have an exponential backoff like https://github.com/deboorn/expbackoffworker built in? This so we can do retries when we hit Digital Ocean Spaces rate limiting. This has been an issue a lot. Especially with cleanups using Laravel Spatie Backups. See https://github.com/spatie/laravel-backup/issues/783 where we discuss the issue.

**Comment by frankdejonge** [comment]
Hi, @jasperf. I'd recommend implementing this outside of Flysystem. The best way, if you want to make this transparent, is to use a decorator around the AWS SDK. This falls outside of the scope for Flysystem. I see Freek suggesting it should be dealt with by Flysystem, but I don't agree with that. In my opinion, Flysystem only concerns itself with making sure all the filesystem have the same API and relatively consistent error reporting (improved in V2 btw), but not with high-level cases like retries of operations or exponential backoff.

**Comment by jasperf** [comment]
@frankdejonge Had to Google Decorator and found https://dev.to/ahmedash95/design-patterns-in-php-decorator-with-laravel-5hk6 which deals with PHP Decorators to wrap functionality in an interface it seems. This to extend its functionality. So this way we would have Laravel using PHP Fly System using S3 Driver wrapped or decorated in an interface to extend its functionality with exponential backoffs. 

This is how I understand this as a junior PHP / Laravel developer anyways. Will see what our senior developer has to say about this. Actually found your decorator class https://github.com/thephpleague/flysystem-adapter-decorator . Perhaps this one could be used as well?

Good to hear that version 2 will deal with error reporting better. That is something that is recommended by Digital Ocean Spaces and Amazon S3. That is recommended besides using exponential backups. Besides the fact that having exponential backups part of PHP Flysystem saving us time I do feel like it would be a useful part of this package. But I also understand your point of view. 

Also surprised the S3 driver itself does not have options for it built in nor the DO API as I would think this is something that is needed often. S3's rate acceptance is much better than DO Spaces so you do not need this tool that quick but still I think most developers wind up needing it. 

For now we will probably use block storage volumes to store images instead of S3 or Digital Ocean Spaces. TransIP [Big Storage (SSD) ](https://www.transip.nl/knowledgebase/artikel/304-wat-is-big-storage/) for example. Saves us the pain dealing with a constant barrage of 503s, the need to create PHP Decorator patterns to have PHP Flysystem AWS S3 Driver work correctly.

Thanks a lot for the feedback though, learned a lot again this Sunday morning. And may still try my hand at this PHP Decorator pattern I am totally new to.

**Comment by frankdejonge** [comment]
@jasperf the decorated should be applied on the S3Client, so that adapter decorator won't help you. You can see an example of a decorator in the V2 test base: https://github.com/thephpleague/flysystem/blob/2.x/src/AwsS3V3/S3ClientStub.php
This decorator proxies all normal calls but changes some behavior, in your case you can also implement a re-try mechanism there.

**Comment by jasperf** [comment]
Thanks for that referral to the S3 Client Stub at the version 2. Going to look into that @frankdejonge .

**Comment by jasperf** [comment]
Now that version 3 is out we may get into less 503s . See https://blog.frankdejonge.nl/flysystem-3-0-0-is-released/ where @frankdejonge mentioned

> The `update` and `write` functions were essentially the same. 

So I assume that on uploading files, reading files and writing files we automatically get less calls. Might still need exponential backoffs but we are going to give V3 a spin soon.
