### ISSUE TITLE
Error when handling positive response on non-existing file

### ISSUE THREAD

**Issue by patrickkusebauch** [thephpleague/flysystem-aws-s3-v3#206]
This one is a doozie. I am not even sure how it is possible, but it happened. Basically I got a response from the API like the file existed (which it doesn't), however it did not include the `content`. Therefore the follow-up processing failed and the package threw an error. Including screenshots to follow along.

![Screenshot from 2020-08-03 20-02-22](https://user-images.githubusercontent.com/1620948/89213047-c72ad200-d5c4-11ea-997c-5dcf96b20da9.png)
Here you can see the place where it is failing - it cannot call a method on `$response['contents']` because the array key does not exist. You can see it here: 
![Screenshot from 2020-08-03 20-03-13](https://user-images.githubusercontent.com/1620948/89213178-fe997e80-d5c4-11ea-835c-441f4397120e.png)
 
If I use the Wub UI of S3, you can see the file really does not exist:
![Screenshot from 2020-08-03 20-03-24](https://user-images.githubusercontent.com/1620948/89213283-22f55b00-d5c5-11ea-9d10-a1dec4fdecee.png)

Before you ask, yes, the configuration is correct, I loop through this code and the other 30+ file that may or may not exist are processed just fine.

**Comment by frankdejonge** [comment]
If you find a way to reproduce this, please open an issue with the information. I'm not able to do so.
