### ISSUE TITLE
Cannot upload large files when passed the `@http` option to stream files

### ISSUE THREAD

**Issue by tstrijdhorst** [thephpleague/flysystem-aws-s3-v3#209]
I was looking for a way to work with file streams and s3, both read and write. Writing worked perfectly when using the `writeStream` method without any options. However, `readStream` did not work out of the box. When I searched for a solution I found this thread: https://github.com/thephpleague/flysystem-aws-s3-v3/issues/124

I implemented the fix suggested in this comment: https://github.com/thephpleague/flysystem-aws-s3-v3/issues/124#issuecomment-330589497

After this `readStream` worked perfectly, so far so good. However, after passing this option I cannot get my `writeStream` to work anymore. It gives me the following error:

```
Found 1 error while validating the input provided for the UploadPart operation:
[UploadId] is missing and is a required parameter
```

If I remove the option than uploading streams work perfectly again but obviously the reading isn't working anymore.

Any suggestion how to get to a situation where I can both read and write streams?

Long shot: @twistor , I know this is a long time ago but do you remember how you came up with this suggestion of including the option? I have looked through the flysystem docs, all the source and most of the aws s3 docs but I didn't find any mention of this magic.

**Comment by frankdejonge** [comment]
@tstrijdhorst this sounds like a bug in the SDK. This should just work.
