### ISSUE TITLE
ErrorException: rewind(): stream does not support seeking since 1.0.26

### ISSUE THREAD

**Issue by ziming** [thephpleague/flysystem-aws-s3-v3#212]
Ever since 1.0.26 when I try to return a MediaStream from spatie medialibrary package I get this error

ErrorException: rewind(): stream does not support seeking

Downgrading this library (flysystem-aws-s3-v3) to 1.0.25 solves the issue for me temporarily.

For context, this is what MediaStream is (tldr: a collection of files to be streamed to the user as a zip download)

https://docs.spatie.be/laravel-medialibrary/v8/downloading-media/downloading-multiple-files/#main

Thank you.

**Comment by frankdejonge** [comment]
Hi @ziming, the streaming defaults changes because of memory consumption. You can set a flag for the previous behaviour here: https://flysystem.thephpleague.com/v1/docs/adapter/aws-s3-v3/#streamed-reads

**Comment by ziming** [comment]
Thanks for the response Frank!

But I'm not sure where in laravel can I pass this flag. Or is this a PR one has to make to spatie media library or laravel framework?

I tried to search for AwsS3Adapter in https://github.com/spatie/laravel-medialibrary repo, I couldn't find a mention of AwsS3Adapter

**Comment by frankdejonge** [comment]
@ziming this should be a setting in laravel's integration, or you can register a custom disk, which is documented here: https://laravel.com/docs/7.x/filesystem#custom-filesystems

**Comment by alexander-schranz** [comment]
@frankdejonge this does currently also effect us in @sulu. Does this currently only effect the aws adapter?
We currently create the adapter instance this way:

https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/MediaBundle/Resources/config/services_storage_s3.xml#L17-L21

**Comment by tomgrohl** [comment]
Does this package follow Semver? I noticed some PHP League packages do. Correct me if I'm wrong but surely this change is a breaking change?

It makes sense to add the option in but wouldn't it make sense to default to false. And default to true on version 2 onwards?

**Comment by frankdejonge** [comment]
@tomgrohl yes it does, but this was an unforeseen side effect. The API remained the same, but usage was affected. In this case I’d rather go for one accident than two, so one BC error.

**Comment by frankdejonge** [comment]
@alexander-schranz this only affects the aws one.

**Comment by alexander-schranz** [comment]
@frankdejonge Thank you. Do you recommend a specific way to detect the mime type of a filesystem resource?

**Comment by frankdejonge** [comment]
You can, since 1.1.0, use your own detection strategy based on `league/mime-type-detections`, using Mimetype::useDetector to set the default one. For 2.0 it'll be a constructor argument. What you can do is extension based mime-type detection.

**Comment by alexander-schranz** [comment]
@frankdejonge Thank you, but it seems `league/mime-type-detections` does not work with a `resource` you always will need to load the whole asset then from teh storage to detect the mime type or I'm wrong?
