### ISSUE TITLE
Can not rewind csv file

### ISSUE THREAD

**Issue by ganeko** [thephpleague/flysystem-aws-s3-v3#213]
We have upgraded from the `1.0.25` version to `1.0.28` and the php's `rewind` method does not return the pointer to the beginning of the file when reading from stream.

Example code,

```
$handle = $mountManager->readStream($path);

$headersA = fgetcsv($handle, null, "\t");
rewind($handle);

$headersB = fgetcsv($handle, null, "\t");
```

The result of this code is for `$headersA` we get the first line of the CSV, but for `$headersB` we get the second line of the csv. The same thing happens as we go through the csv, the rewind cannot return to the beginning.

This test code works fine in, at least, `1.0.25` version.

**Comment by frankdejonge** [comment]
You can set the streamed reads constructor Boolean to false your allow rewinds. It was a BC mistake, sorry for the inconvenience.

**Comment by ganeko** [comment]
Oh thank you very much.  Maybe this has been communicated in a changelog and we have missed it?  Thank you very much for your work!

**Comment by frankdejonge** [comment]
I've added a more elaborate changelog entry, does that explain it better? https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/changelog.md

**Comment by ganeko** [comment]
> I've added a more elaborate changelog entry, does that explain it better? https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/changelog.md

Thanks @frankdejonge . Yes, now everything is clear. In fact, we have already been able to change it in our environment and everything is working correctly. Great job mate!
