### ISSUE TITLE
HTTP streams breaking image read from S3

### ISSUE THREAD

**Issue by mattacular** [thephpleague/flysystem-aws-s3-v3#216]
Running a Drupal application using:
Drupal Flysystem
1.0.25

**Comment by frankdejonge** [comment]
You can set the last constructor argument to false.

**Comment by mattacular** [comment]
Sorry, submitted this early by mistake. I was planning to provide more information later. Thanks for getting back to me despite such a terrible issue report. I did end up finding a way to set that argument to `false` via existing configuration path (as we do not use this library directly but rather it is a dependency of https://www.drupal.org/project/flysystem_s3). Everything is working again 👍 

Do you have any idea why this broke? I'm more curious why it broke in the way that it did: without any distinct error.

The behavior when trying to request an image after this #211  update (ie. Drupal app reading an image obj from S3 and writing it back out as the response). The response headers were set up correctly with the content-length and type appropriate for the image but no body would ever be transferred. Curl would eventually timeout with "0 bytes received", Chrome browser would eventually timeout with "(HTTP)200, content mismatch" error (due to receiving 0 bytes). Took quite a bit of digging to realize what was going on since it was a dependency of a dependency changing.
