### ISSUE TITLE
Problem with uploading big files with Laravel to S3

### ISSUE THREAD

**Issue by TAvsec** [thephpleague/flysystem-aws-s3-v3#217]
I'm stuck with this specific problem for two days and can't find a solution.

So I have Laravel 7.0 project hosted on AWS Elastic Beanstalk, which is running fine. I also have S3 bucket, used for saving uploaded videos, which are uploaded to server via user form.

The problem is, smaller files(< 10 MB) are uploaded without a problem. But once it comes to bigger files, `Storage::disk('s3')->put('videos/lorem.mp4', fopen($request->file('file'), 'r+'));` method returns `false` and file is not uploaded to S3. If I use `'public'` disk instead of `'s3'` disk, file is uploaded without a problem.

I also tried to upload file manually via AWS CLI with the same IAM user and it was uploaded without a problem.

PHP and nginx configuration are correctly configured to accept big files.

**Comment by rafaeltovar** [comment]
Have you tried with `putStream` method?

```php
Storage::disk('s3')->putStream('videos/lorem.mp4', fopen($request->file('file'), 'r+'));
```

**Comment by frankdejonge** [comment]
@TAvsec this sounds like a Laravel issue, not a Flysystem issue. Have you seen the suggestion above?
