### ISSUE TITLE
Why default stream reads?

### ISSUE THREAD

**Issue by schmunk42** [thephpleague/flysystem-aws-s3-v3#218]
The change in https://github.com/thephpleague/flysystem-aws-s3-v3/commit/c73ebc5b78076e971ec64fdab8a5a956d118b160 to default stream reads broke several AWS S3 buckets for us.

What was the rationale behind it? Since AWS states in https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

> Streams opened in “r” mode only allow data to be read from the stream, and are not seekable by default.

I don't see any `stream_context_create()` calls to make a stream seekable.

Related: 
- https://github.com/thephpleague/flysystem-aws-s3-v3/issues/212
- https://github.com/yiisoft/yii2/pull/18290

---

(addon)
In any case, please create a minor version for changed defaults, not just a patch release.

**Comment by Berdir** [comment]
This also seems to to break the Drupal integration: https://www.drupal.org/project/flysystem_s3

What's happening there is that fstat() on the stream no longer works.

See \Twistor\FlysystemStreamWrapper::stream_stat (https://github.com/twistor/flysystem-stream-wrapper/blob/master/src/FlysystemStreamWrapper.php#L606), which calls StreamUtils::getSize() which does a fstat() on the stream and that returns FALSE. 

So agreed that this seems to be an unfortunate behavior change for a patch release.

**Comment by frankdejonge** [comment]
Hi, it is better for memory consumption to stream reads. I do apologize for the unintended breaking of functionality.
