### ISSUE TITLE
Using getMetadata method on directories

### ISSUE THREAD

**Issue by diego-sorribas** [thephpleague/flysystem-aws-s3-v3#219]
Hi there! I know that for S3 there are not directories but to simplify the explanation I want to know if I'm doing something wrong.
I want to get the metadata of a directory but when the Filesystem builds the key it doesn't append a slash at the end like for example it's done in the doesDirectoryExist method of the adapter. I think that the Filesystem removes all slashes in the key, because if I call directly to the adapter with a slash at the end its works.

Maybe is not a good practice to obtain directory metadata?

Thanks!

**Comment by frankdejonge** [comment]
Hi @diego-sorribas, it depends on the case. There are reasons directories don't exist for filesystems like S3. But perhaps I can help you out in your case. So feel free to share it and perhaps I can help.
