### ISSUE TITLE
plugin listPaths doesn't work

### ISSUE THREAD

**Issue by zexz** [thephpleague/flysystem-aws-s3-v3#22]
works fine when using aws s3 v2 adepter, however it returns empty array when using v3 adapter with same settings

**Comment by frankdejonge** [comment]
@zexz I'm guessing this is caused by something else. I just tried this and it works as expected.

**Comment by zexz** [comment]
@frankdejonge i'm sorry, i was not specific enough
listPaths is showing files in specified path, but it won't show any "subfolders" (since i switched to v3)
i've tried even to setVisibility of those subfolders to "public" - but it does not help

**Comment by frankdejonge** [comment]
@zexz did you set the listing to be recursive? so `$filesystem->listPaths($dirname, true);`

**Comment by zexz** [comment]
sure, tried with recursive and without
it is returning all the files in subfolders like it should, but it seems that only folders are like "filtered out"
i've even tried to use this construction: 
```
			$objects = $client->getIterator('ListObjects', array(
				"Bucket" => S3_BUCKET,
				"Prefix" => ARCHIVE_FOLDER
			));
			foreach ($objects as $object) {
				echo $object['Key'] . "<br>";
			}
```
and it shows only files there

but when i used this one:
```
			$objects = $client->listObjects(array(
				"Bucket"    => S3_BUCKET,
				"Prefix"    => ARCHIVE_FOLDER
			));
			foreach ($objects as $object) {
				echo $object['Key'] . "<br>";
			}
```
i was able to see folders in the list received

so as far as i understand the issue is not with S3 Adapter, but with S3 Client on my end ?

**Comment by frankdejonge** [comment]
@zexz weird, when I try this I just get the directories.

**Comment by frankdejonge** [comment]
@zexz are you using the latest sdk version and the latest adapter version?

**Comment by zexz** [comment]
@frankdejonge i think i am, just removed everything regarding aws sdk and flysystem and installed it like this:

```
composer require league/flysystem
composer require league/flysystem-aws-s3-v3
```

same issue =(

**Comment by zexz** [comment]
this is what composer saying about "update"

```
zExzs-MacBook-Pro:flysystem zexz$ composer update league/flysystem-aws-s3-v3
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
zExzs-MacBook-Pro:flysystem zexz$ composer update league/flysystem
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by frankdejonge** [comment]
For my dummy bucket I just ran `print_r($filesystem->listPaths('', true));` which results in:

```
Array
(
    [0] => dirname/file.txt
    [1] => dirname/newdir
    [2] => file.txt
    [3] => new_dir
    [4] => new_dir/event (5).ics
    [5] => stored.zip
    [6] => streamed.txt
)
```

Also, on the latest of everything.

**Comment by zexz** [comment]
@frankdejonge i was trying to see listPaths for other folders as well - and can say that some folders are shown in my case and some aren't. 
I see strange output in your folder list too, look at the element 3 and 4, 3 is the folder, and 4 is the item inside the folder - however if you will look at the very beginning of your array - elements 0,1 are items of the folder dirname/ but you don't have it in the list
p.s. i was thinking that listPaths should show only folders and listContents should show files
