### ISSUE TITLE
Argument 1 passed to League\Flysystem\AwsS3v3\AwsS3Adapter::__construct() must be an instance of Aws\S3\S3ClientInterface, instance of Aws\S3\S3Client given

### ISSUE THREAD

**Issue by amitsharma8891** [thephpleague/flysystem-aws-s3-v3#220]
I am trying upload image on S3 bucket, using laravel framework but getting bellow error:

`Argument 1 passed to League\Flysystem\AwsS3v3\AwsS3Adapter::__construct() must be an instance of Aws\S3\S3ClientInterface, instance of Aws\S3\S3Client given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php on line 208 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to League\\Flysystem\\AwsS3v3\\AwsS3Adapter::__construct() must be an instance of Aws\\S3\\S3ClientInterface, instance of Aws\\S3\\S3Client given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php on line 208 at /var/www/html/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php:85) 
`

My composer.json contains:

```
...
"aws/aws-sdk-php": "3.0",
"laravel/framework": "5.7.*",
"league/flysystem-aws-s3-v3": "~1.0",
"league/flysystem-cached-adapter": "1.0",
...
```

AWS s3 user permission - AmazonS3FullAccess

AWS s3 bucket - policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectVersion",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::[bucket-name]/*"
        }
    ]
}
```

Any help would be highly appreciated

Thanks

**Comment by senguttuvang** [comment]
@amitsharma8891 We encountered the same issue. Can you please guide us on how you resolved it?

**Comment by frankdejonge** [comment]
@senguttuvang my guess is updating the dependencies did the trick.

**Comment by senguttuvang** [comment]
Actually, it worked for us but I can see the exception in our exception tracking system for other users. I suspect it should have behaved the same for all users. I think the requests are resolving mistakenly for another server that had this dependency issue. Anyhow, thanks for the hint, will investigate further
