### ISSUE TITLE
DigitalOcean Spaces "503 Slow Down"

### ISSUE THREAD

**Issue by mattrothenberg** [thephpleague/flysystem-aws-s3-v3#221]
Hello!

I've got a [Statamic 3](https://statamic.com/) project that's using `flysystem-aws-s3-v3` to persist assets to a Digital Ocean spaces bucket.

Setting things up was a breeze, but I've run into a persistent issue that I'd love some help debugging, as I'm not sure whether it's an issue in the Statamic source code, a misconfiguration on my end, or something to do with this project.

While I seem to be able to upload/delete images from Statamic's asset library UI, I always run into this particular error **503 Slow Down** when editing a collection. What's particularly weird about this is that my site has **zero** web traffic, I have 1 image uploaded to DO spaces, and I'm ostensibly the only user making requests (through a web browser, no less). I'm not sure how I would ever be able to cross such a rate-limiting threshold.

<img width="894" alt="Screen Shot 2020-10-12 at 8 38 51 AM" src="https://user-images.githubusercontent.com/5148596/95747389-5c51e300-0c66-11eb-8594-17db976e1a91.png">

Any advice on where to start digging in further? I see in the stack trace that this is coming from:

```php
League\Flysystem\AwsS3v3\AwsS3Adapter::has
vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php:233

if ($this->s3Client->doesObjectExist($this->bucket, $location, $this->options)) {
  return true;
}
```

Thank you!

**Comment by frankdejonge** [comment]
There is rate-limiting on the DO/S3 side. I don't know enough about Statamic to help you out with this one. Flysystem just proxies calls in a particular format, we don't influence how often calls are being made. You can disable file existence assertions using a configuration setting: https://flysystem.thephpleague.com/v1/docs/advanced/performance/ but other than that I really can't help you. Sorry about that.

**Comment by mattrothenberg** [comment]
@frankdejonge no worries, thank you so much for the prompt reply! Will dig into this further ❤️

**Comment by frankdejonge** [comment]
Good luck!
