### ISSUE TITLE
Region must be a valid RFC host label.

### ISSUE THREAD

**Issue by satishjunghareewebcore** [thephpleague/flysystem-aws-s3-v3#224]
I am passing credentials to env file and installed this sdk still getting following issue.

AWS_ACCESS_KEY_ID=************
AWS_SECRET_ACCESS_KEY=************
AWS_DEFAULT_REGION=************
AWS_BUCKET=************

SDK Version : ^1.0

> {
    "message": "Region must be a valid RFC host label.",
    "exception": "Aws\\Exception\\InvalidRegionException",
    "file": "/var/www/unsold/nmiwebsite/vendor/aws/aws-sdk-php/src/ClientResolver.php",
    "line": 543,
    "trace": [

**Comment by frankdejonge** [comment]
@satishjunghareewebcore please open an issue here: https://github.com/aws/aws-sdk-php

**Comment by satishjunghareewebcore** [comment]
https://github.com/aws/aws-sdk-php/issues/2126
i have created issue over there, please check.

**Comment by frankdejonge** [comment]
@satishjunghareewebcore I'm not the maintainer of that library. Can't really help you there, sorry.

**Comment by OldRustyDayton** [comment]
> @satishjunghareewebcore please open an issue here: https://github.com/aws/aws-sdk-php

Was this ever solved? I am experiencing the same thing.
