### ISSUE TITLE
Copy, move is not working for files.

### ISSUE THREAD

**Issue by naczu** [thephpleague/flysystem-aws-s3-v3#225]
Hi, 

I use digitalocean space storage for my production and "league/flysystem-aws-s3-v3": "^1.0" composer package. 

When I try to move a file it returns false and file is not moving (or renaming). All other functions (get, put, download, delete) are working as expected.

**Comment by frankdejonge** [comment]
That is a problem on DigitalOcean's side or with the AWS SDK. Nothing I can do from this end, sorry.
