### ISSUE TITLE
SignatureDoesNotMatch issue on DigitalOcean Spaces

### ISSUE THREAD

**Issue by oxodesign** [thephpleague/flysystem-aws-s3-v3#226]
Hi 

Since yesterday we are getting this error "SignatureDoesNotMatch" when trying to upload files to Digital Ocean Spaces.

It may be related to time change from Summer time to Winter time!? 

Does anyone know what it can be? And how to fix it?!

Thanks in advance.

**Comment by oxodesign** [comment]
After some hours of investigation we found out that when we defined BUCKET name in our config we had "<BUCKETNAME>/<FOLDERNAME>" where <FOLDERNAME> is the root folder we wanted to upload assets to (some kind of prefix).

This solution worked before (dont ask me why we have done this), but its not working anymore!

Hope this will help others!

**Comment by frankdejonge** [comment]
@oxodesign thank you for coming back to close the issue 👍
