### ISSUE TITLE
Documentation error 

### ISSUE THREAD

**Issue by alainsharemat** [thephpleague/flysystem-aws-s3-v3#232]
Hello,

maybe I'm wrong but it looks like the class is named `AwsS3V3Adapter` instead of `AwsS3Adapter` on the doc : 
https://flysystem.thephpleague.com/v1/docs/adapter/aws-s3-v3/

Or is there something I missed ?

Thank you

**Comment by realjay007** [comment]
The hosted version on composer is also different. I had to install the github version using `composer require league/flysystem-aws-s3-v3:dev-master` for it to work.

**Comment by frankdejonge** [comment]
I've corrected the docs.

**Comment by realjay007** [comment]
While this works, I think the major problem is the mismatch between the code hosted here on github and that hosted on composer.

**Comment by frankdejonge** [comment]
@realjay007 it's not really clear for me what you are referring to. The latest release is different, it's 2.0. If you want to install 1.0 you should not use dev-master, but you should specify version something long the lines of `composer require league/flysystem-aws-s3-v3:^1.1.3`.
