### ISSUE TITLE
Requirement could not be resolved

### ISSUE THREAD

**Issue by BernardA** [thephpleague/flysystem-aws-s3-v3#234]
Getting the following error when running  `composer require league/flysystem-aws-s3-v3`:

     Your requirements could not be resolved to an installable set of packages.

       Problem 1
         - Can only install one of: league/flysystem[2.0.0, 1.1.3].
         - Can only install one of: league/flysystem[2.0.0, 1.1.3].
         - Can only install one of: league/flysystem[2.0.0, 1.1.3].
         - league/flysystem-aws-s3-v3 2.0.0 requires league/flysystem ^2.0.0 -> satisfiable by league/flysystem[2.0.0].
         - Installation request for league/flysystem-aws-s3-v3 ^2.0 -> satisfiable by league/flysystem-aws-s3-v3[2.0.0].
         - Installation request for league/flysystem (locked at 1.1.3) -> satisfiable by league/flysystem[1.1.3].

Before that I did run:

     composer require oneup/flysystem-bundle  
     composer require aws/aws-sdk-php

So that my composer.json looks like:

      "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/api-pack": "^1.2",
        "aws/aws-sdk-php": "^3.168",
        "beberlei/doctrineextensions": "^1.3",
        "gesdinet/jwt-refresh-token-bundle": "^0.7.1",
        "google/apiclient": "^2.0",
        "lexik/jwt-authentication-bundle": "^2.6",
        "oneup/flysystem-bundle": "^3.6",
        "sensio/framework-extra-bundle": "^5.4",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/amazon-mailer": "4.4.*",
        "symfony/console": "^4.0",
        "symfony/dotenv": "^4.0",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "^4.0",
        "symfony/google-mailer": "4.4.*",
        "symfony/http-client": "4.4.*",
        "symfony/mailer": "4.4.*",
        "symfony/monolog-bundle": "^3.6",
        "symfony/orm-pack": "^1.0",
        "symfony/serializer-pack": "^1.0",
        "symfony/translation": "4.4.*",
        "symfony/yaml": "^4.0",
        "vich/uploader-bundle": "^1.10",
        "webonyx/graphql-php": "^0.13.8"
    },

Looking at composer.lock I see that the version of `league/flysystem` is `1.1.3' which I believe was put there for `oneup/flysystem`

         "name": "league/flysystem",
            "version": "1.1.3",

I did try to force  update to `league/flysystem@2.0.0` running 
`composer update oneup/flysystem --with-dependencies`
but that did not change anything.

**Comment by frankdejonge** [comment]
The oneup bundle doesn't support flysystem 2 yet, so if you want to install flysystem, you need to use the previous major version.

**Comment by BernardA** [comment]
Like so `composer require league/flysystem-aws-s3-v3:1.0.29`?
That seem to have worked.
