### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by MagnusDot** [thephpleague/flysystem-aws-s3-v3#235]
Hello, I am developing an application and I think support for php 8 would be great!

![image](https://user-images.githubusercontent.com/39904918/103371673-5f73a700-4ad0-11eb-9a7a-ed2013fd5f9e.png)

**Comment by frankdejonge** [comment]
Hi @MagnusDot,

Your error is not about PHP 8 support, it's about a version 1 or 2 conflict. You're using Laravel and Composer is trying to install version 2, which is not compatible. You should install it like `composer require league/flysystem-aws-s3-v3:^1.0`.

**Comment by MagnusDot** [comment]
sry thx for the help

**Comment by tcox-enrollfirst** [comment]
Was having same issue.  Thanks @frankdejonge

**Comment by digitaltim-de** [comment]
Same Issue and fixed. Thanks @frankdejonge
