### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by christianantonyquero** [thephpleague/flysystem-aws-s3-v3#236]
League\Flysystem\AwsS3v3\AwsS3Adapter::__construct(): Argument #1 ($client) must be of type Aws\S3Client, Aws\S3\S3Client given, called invendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php on line 214

**Comment by frankdejonge** [comment]
1: learn how to file an issue on github
2: update your dependencies
