### ISSUE TITLE
S3 upload exception is not converted to filesystem exception

### ISSUE THREAD

**Issue by andrew-demb** [thephpleague/flysystem-aws-s3-v3#237]
In v1 versions, internal AWS exception caught and converted to failed result, so client code is required to check result only for `false` value.
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/4e25cc0582a36a786c31115e419c6e40498f6972/src/AwsS3Adapter.php#L607-L609

In v2 versions, internal AWS exception is not caught in any way and doesn't convert to documented (https://flysystem.thephpleague.com/v2/docs/usage/exception-handling/ and example for `writeStream` https://github.com/thephpleague/flysystem/blob/7373c4baf04c6cdf88b961486e89a40238c46c53/src/FilesystemWriter.php#L15-L21) as expected exceptions from flysystem's adapters  
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/ac4a9a30c55adfcfa90b800407ead2eb09ce8376/AwsS3V3Adapter.php#L152

Is it intended, that client code now should catch these (AWS) errors manually?

**Comment by aleksbrgt** [comment]
Yes this choice is strange to me too. It makes it needlessly difficult to debug and impossible to report useful errors outside of debugging.

Having to test each method to check if they return false before continuing to the next call is really impractical.

**Comment by aleksbrgt** [comment]
More or less related to #246 too

**Comment by frankdejonge** [comment]
This is fixed in 2.0.5
