### ISSUE TITLE
Error: Class 'League\Flysystem\AwsS3v3\AwsS3V3Adapter' not found

### ISSUE THREAD

**Issue by jupitern** [thephpleague/flysystem-aws-s3-v3#243]
Hi,
I have upgraded my code to v2 and now I can't seem to get it working. I get the error bellow althouth the file exists in the correct path in vendor directory . 
Error: Class 'League\Flysystem\AwsS3v3\AwsS3V3Adapter' not found 

In my composer json I have the lines bellow and it installs 2.0.3 of both packages
"league/flysystem": "2.0.*",
"league/flysystem-aws-s3-v3": "2.0.*",

My code:

use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3V3Adapter;
use League\Flysystem\Filesystem as FlySystem;

$client     = new S3Client($s3Configs);
$adapter    = new AwsS3V3Adapter($client, $configs["bucket"], $container);
$filesystem = new FlySystem($adapter, ["visibility" => "public"]);

I can't understand the issue. help would be welcome.

**Comment by servdebtdev** [comment]
fixed. please ignore

**Comment by jupitern** [comment]
fixed. please ignore
