### ISSUE TITLE
PHP 8.0.0 Version Problem

### ISSUE THREAD

**Issue by ersoyfilinte** [thephpleague/flysystem-aws-s3-v3#244]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/flysystem-aws-s3-v3[2.0.0, ..., 2.x-dev] require league/flysystem ^2.0.0 -> found league/flysystem[2.0.0-alpha.1, ..., 2.x-dev] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match.
Make sure you list it as an argument for the update command.
    - league/flysystem-aws-s3-v3[2.0.0-alpha.1, ..., 2.0.0-RC1] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires league/flysystem-aws-s3-v3 ^2.0 -> satisfiable by league/flysystem-aws-s3-v3[2.0.0-alpha.1, ..., 2.x-dev].
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Composer.json file:

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "ext-json": "*",
        "ext-pdo": "*",
        "awobaz/compoships": "^2.0",
        "aws/aws-sdk-php": "^3.172",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/horizon": "^5.6",
        "laravel/jetstream": "^2.1",
        "laravel/sanctum": "^2.6",
        "laravel/telescope": "^4.4",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "maatwebsite/excel": "^3.1"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

**Comment by thyagomuris** [comment]
same problem here

**Comment by rosen91** [comment]
Same here

**Comment by frankdejonge** [comment]
`composer require league/flysystem-aws-s3-v3:^1.1`

**Comment by rosen91** [comment]
Can't seem to find that version on packagist? 
Could not find package league/flysystem-aws-s3-v3 in a version matching ^1.1

**Comment by frankdejonge** [comment]
`composer require league/flysystem-aws-s3-v3:^1.0`

**Comment by ShuaiZhangFmym** [comment]
Same here
