### ISSUE TITLE
Unable to install on laravel v8.31.0

### ISSUE THREAD

**Issue by DeeJ** [thephpleague/flysystem-aws-s3-v3#245]
Unable to install the latest version of this package on laravel v8.31.0

Running `composer require league/flysystem-aws-s3-v3` returns the following error. Looks like this package is trying to use flysystem 2 however laravel 8 ha flysystem  pinned to v1.1.3

Problem 1
    - league/flysystem-aws-s3-v3[2.0.0, ..., 2.x-dev] require league/flysystem ^2.0.0 -> found league/flysystem[2.0.0-alpha.1, ..., 2.x-dev] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - league/flysystem-aws-s3-v3[2.0.0-alpha.1, ..., 2.0.0-alpha.2] require league/flysystem 2.0.0-alpha.1 -> found league/flysystem[2.0.0-alpha.1] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - league/flysystem-aws-s3-v3[2.0.0-alpha.4, ..., 2.0.0-beta.1] require league/flysystem 2.0.0-alpha.3 -> found league/flysystem[2.0.0-alpha.3] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - league/flysystem-aws-s3-v3[2.0.0-beta.2, ..., 2.0.0-beta.3] require league/flysystem ^2.0.0-beta.1 -> found league/flysystem[2.0.0-beta.1, ..., 2.x-dev] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - league/flysystem-aws-s3-v3 2.0.0-RC1 requires league/flysystem ^2.0.0-RC1 -> found league/flysystem[2.0.0-RC1, ..., 2.x-dev] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires league/flysystem-aws-s3-v3 ^2.0 -> satisfiable by league/flysystem-aws-s3-v3[2.0.0-alpha.1, ..., 2.x-dev].
    
I can still install version 1 `(composer require league/flysystem-aws-s3-v3:1)` however it would be nice to get the latest version

**Comment by frankdejonge** [comment]
@DeeJ you can't get v2 because laravel doesn't support it yet. You can use the a preview version which is league/flysystem-v2-preview-aws-s3-v3, but it's not tied into laravel's tooling.

**Comment by DeeJ** [comment]
Oki doki, thanks :-)

**Comment by raisonon** [comment]
@DeeJ  A SO ref here too: https://stackoverflow.com/a/65002651/2468603
