### ISSUE TITLE
bucket being attached at beginning of endpoint url

### ISSUE THREAD

**Issue by devildog3261** [thephpleague/flysystem-aws-s3-v3#250]
When connecting to digital ocean spaces or aws S3, the bucket is being attached at the beginning of the connection  url.

Generated Connection URL
`images.https://nyc3.digitaloceanspaces.com`

ENV
`DIGITALOCEAN_SPACES_BUCKET=images`

ERROR
`exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "images.https://nyc3.digitaloceanspaces.com"; AWS HTTP error: cURL error 1: Protocol "images.https" not supported or disabled in libcurl (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for images.https://nyc3.digitaloceanspaces.com'`

**Comment by anasbadrusalam** [comment]
Downgrade aws/aws-sdk-php to version 3.174.3 work for me

**Comment by devildog3261** [comment]
That did not work for me, its still appending the bucket before the https://

If, I change DIGITALOCEAN_SPACES_ENDPOINT env variable from:

`https://nyc3.digitaloceanspaces.com` to: `nyc3.digitaloceanspaces.com`

then it creates a URL like this:

`//images.nyc3.digitaloceanspaces.com/images.nyc3.digitaloceanspaces.com`

**Comment by johnpuddephatt** [comment]
Same here, experiencing the same problem! Will let you know if I get anywhere with resolving.

**Comment by johnpuddephatt** [comment]
It looks like there's an issue in aws-sdk-php that popped up in version 3.173 then went away but has reappeared in 3.175.0 judging by [this issue](https://github.com/aws/aws-sdk-php/issues/2209)

I had 3.175.0 installed but did `composer require aws/aws-sdk-php:3.173.23` and now everything seems to be working.

Note that in my config I now don't have a URL value, only an endpoint (https://[REGION].digitaloceanspaces.com), region, and bucket name.

**Comment by frankdejonge** [comment]
For this category of issues you can always assume this is a AWS SDK issue and is not influenced by Flysystem. Thanks for linking to the issue and specifying how to resolve it @johnpuddephatt 👍

I'll close the issue now since there's nothing on this end.

**Comment by devildog3261** [comment]
@johnpuddephatt this worked perfectly! Thank you very much. I had been trying multiple different versions but was still having issues. v3.173.23 works!
