### ISSUE TITLE
[Question] Difference between v1 and v2

### ISSUE THREAD

**Issue by shehi** [thephpleague/flysystem-aws-s3-v3#255]
Couldn't see any differences in the code between v1 and 2.  https://github.com/thephpleague/flysystem-aws-s3-v3/compare/1.0.29...2.0.5 - So it was just a version bump?

**Comment by frankdejonge** [comment]
Hi @shehi, they are separate branched with independent histories, this is why you can't compare them. You can look at the docs to see what the difference is. TL;RD: stricter typing, generator based listings, a full-fledged exceptions system.
