### ISSUE TITLE
League\Flysystem\AwsS3v3\AwsS3Adapter Not fund in laravel 8

### ISSUE THREAD

**Issue by aureliotechnology** [thephpleague/flysystem-aws-s3-v3#258]
I'm using laravel 8 and I'm getting the following error:

> Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found

I know the incompatibility of version 2, my composer is like this:

> "league/flysystem-aws-s3-v3": "^1.0",

I checked the files and they're all in the vendor folder, I'm really lost on this error. I would love to use this package, it exactly meets my demand.

Thanks to anyone who can help.

**Comment by iaicam** [comment]
This isn't related to just laravel 8. I have it in a normal PHP project. Using 2.1.1 of flysystem and 2.1.0 of this package.

**Comment by iaicam** [comment]
I've created a demo repo that suffers from this problem. https://github.com/iaicam/flysystem-error

**Comment by frankdejonge** [comment]
The class `League\Flysystem\AwsS3v3\AwsS3Adapter` does not exist, but `League\Flysystem\AwsS3V3\AwsS3Adapter` does.
