### ISSUE TITLE
`503 Service Unavailable` response

### ISSUE THREAD

**Issue by shuujin23** [thephpleague/flysystem-aws-s3-v3#265]
Hi,
I'm trying to upload a file via laravel server to my s3 server but i got this error:

> 
Error executing "PutObject" on "pathfile"; AWS HTTP error: Server error: `PUT pathfile` resulted in a `503 Service Unavailable` response:

this is my code 
`Storage::disk('s3')->put('path', $file, 'public');`

i already ask to my s3 storage provider and the server is doing okay.
How to resolve this issue?
thanks in advance

**Comment by frankdejonge** [comment]
Hi @shuujin23,

Often with S3 providers there are incompatibilities with the S3 client from AWS. This is an S3 client issue, not a flysystem issue.

**Comment by shuujin23** [comment]
i see. Thank you for the response
