### ISSUE TITLE
Trouble getting lastModified and size

### ISSUE THREAD

**Issue by charleswolfe** [thephpleague/flysystem-aws-s3-v3#268]
I have a file on S3, 838 MB in size, when I try to read its lastModified or its size, I get an error

`
"Error executing "ListObjects" on "https://s3.amazonaws.com/mydomain.com?prefix=bigfile.zip%2F&max-keys=1&encoding-type=url"; AWS HTTP error: fwrite(): Write of 16384 bytes failed with errno=28 No space left on device"`

Works on smaller files.

**Comment by charleswolfe** [comment]
I cant even recreate this, I'm closing as there's no way the problem is with this package

**Comment by frankdejonge** [comment]
Thanks for coming back to close this 👍

**Comment by charleswolfe** [comment]
No problem, root cause was that a bucket didnt have correct permissions
