### ISSUE TITLE
S3Exception in WrappedHttpHandler.php line 162 when using Storage::put();

### ISSUE THREAD

**Issue by EwanValentine** [thephpleague/flysystem-aws-s3-v3#27]
I'm just having a snag with the Storage facade in Laravel 5.1 when using S3.

I have the following code in a controller:

```
    $file = $request->file('file');

    $extension = $file->getClientOriginalExtension();

    $filename = date('d-m-Y').'_'.$request->get('author').'.'.$extension;
    Storage::put($filename, $file);
```

However I get the following error:

S3Exception in WrappedHttpHandler.php line 162: Error executing "HeadObject" on "https://s3-eu-west-1.amazonaws.com/[REDACTED]/10-06-2015_my%20file.jpg"; AWS HTTP error: Use of undefined constant CURLOPT_PROTOCOLS - assumed 'CURLOPT_PROTOCOLS'

I have cURL installed along with php5-curl on Ubuntu 14.04. I'm using HHVM 3.7.

Cheers in advance!

**Comment by frankdejonge** [comment]
@EwanValentine Hi, this seems to be an issue with the SDK itself, not with this adapter nor with laravel. Perhaps create an issue on their repository, they'll know more about this.

**Comment by frankdejonge** [comment]
@EwanValentine are you sure you enabled the mod too?

**Comment by EwanValentine** [comment]
@frankdejonge I figured this out, curl setopts wasn't compatible in HHVM 3.7, upgrading to 3.8.0-dev fixed this temporarily. This shouldn't be an issue in the next stable version

**Comment by frankdejonge** [comment]
@EwanValentine good to hear, and thanks for coming back and closing the issue :+1:

**Comment by EwanValentine** [comment]
Not a problem :)
