### ISSUE TITLE
503 Slow Down error in DigitalOcean Spaces requests

### ISSUE THREAD

**Issue by davimatos** [thephpleague/flysystem-aws-s3-v3#278]
Hi!

I'm using this library to manipulate files on an s3 drive at DigitalOcean Spaces. The following API error has been returned lately:

```
exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjects"

AWS HTTP error: Server error: GET https://static-yeloo-01.sfo2.digitaloceanspaces.com/?prefix=rsss%2Fnews%2Ftmp%2FphpHFXnGY%2F&max-keys=1&encoding-type=url in a 503 Slow Down response:
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>SlowDown</Code>
<Message>Reduce your request rate.</Message>
</Error (truncated...)
SlowDown (server): Reduce your request rate. - <?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>SlowDown</Code>
<Message>Reduce your request rate.</Message>
</Error>
```

I'm not sure why this error is showing, as my application only uploads profile images and some small size videos, it doesn't have a request flow to reach the request limits per second. The tokens and configuration data are all correct as well.

In contact with the DigitalOcean support team, they also said that there is no overload on my drive for this lock to be happening and asked me to check if it could be something in the library that I use to do this manipulation.

I use the library with Laravel, I already tried to update the version to the latest one, use the option "disable_asserts" to improve the performance, but the error still persists.

Has anyone experienced this problem or know what I can do to fix it?

**Comment by frankdejonge** [comment]
Hi @davimatos can you tried issuing the request directly from the SDK? The error message you're getting is a AWS SDK one, and there's not really something that indicates that the issue would be caused by flysystem (even if that's the interface you're using).

**Comment by davimatos** [comment]
I identified that it was an issue where I was trying to delete an old file when changed. Apparently I was calling more than once and this was generating this error on the server. My bad!

Thanks for replying @frankdejonge !
