### ISSUE TITLE
Deprecation note on PHP 8.1

### ISSUE THREAD

**Issue by lptn** [thephpleague/flysystem-aws-s3-v3#279]
`ltrim(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php on line 537`

**Comment by RSpeekenbrink** [comment]
This is on version 1.0.29

**Comment by lptn** [comment]
ph, sorry, I forget this package has a new major version. Fortunately, Laravel will use it for next Laravel major version
