### ISSUE TITLE
[BUG] CacheControl option not work

### ISSUE THREAD

**Issue by abozhinov** [thephpleague/flysystem-aws-s3-v3#282]
Hi,
options didn't apply as PARAMS when merge configs line: 172 ->  $options = $this->createOptionsFromConfig($config); 

<img width="537" alt="Screenshot 2022-02-09 at 21 51 54" src="https://user-images.githubusercontent.com/1404839/153279365-e52b479d-fdea-4e60-845d-5979de320a7a.png">

**Comment by frankdejonge** [comment]
Hi, which versions (adapter/flysystem/bundle) do you have installed?

**Comment by ankurk91** [comment]
It is no longer working in Laravel v9 as well.

This line is not merging the $options that were passed via constructor

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/3668f4aeafc08a463195a514d52b05d603cb981e/src/AwsS3Adapter.php#L589

**Comment by ankurk91** [comment]
@frankdejonge 
If you want more info please let me know, i really want this to be fixed since we have apps running in production.

**Comment by frankdejonge** [comment]
@ankurk91 it's my holiday, but I just fixed this and released a new version. To be frank with you, you could have pushed this forward by trying to fix it yourself, or even by PR'ing a test case that shows what is going wrong. For somebody who identifies as an open source fanatic, you don't act like it.
