### ISSUE TITLE
Feature request : expose client through getClient()

### ISSUE THREAD

**Issue by marcelopm** [thephpleague/flysystem-aws-s3-v3#284]
We used to be able to get the adapter's client via [getClient()](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L117)

It would be great if we could continue to do so while using v3.x, since that's the compatible version with Laravel 9 : https://laravel.com/docs/9.x/filesystem#s3-driver-configuration

**Comment by frankdejonge** [comment]
This was removed because Flysystem is not a service locator.

**Comment by frankdejonge** [comment]
@driesvints is there a way that laravel users can get access to the AWS SDK without using Flysystem as a service locator? I'd like to link to the docs, I keep getting this question but really strongly disagree it's a responsibility of Flysystem.

**Comment by introwit** [comment]
the current hack I am using is doing `$s3Client = resolve('Aws\S3\S3Client');`

**Comment by frankdejonge** [comment]
@introwit if that works, why would you want to resolve it via Flysystem?

**Comment by marcelopm** [comment]
I don't think the hack above will provide us with the same functionality as it, probably, lacks the configuration passed to the adaptor.

**Comment by driesvints** [comment]
Heya. Someone sent in a way to retrieve the client from Laravel's S3 adapter. It'll be in next Tuesday's release: https://github.com/laravel/framework/pull/41079

**Comment by jszobody** [comment]
If someone needs this before next Tuesday, you can macro it in for now:

```
Illuminate\Filesystem\AwsS3V3Adapter::macro('getClient', fn() => $this->client);
```

**Comment by d3v4nt** [comment]
> If someone needs this before next Tuesday, you can macro it in for now:
> 
> ```
> Illuminate\Filesystem\AwsS3V3Adapter::macro('getClient', fn() => $this->client);
> ```

this is cool and all but where do you get the client? 😅
