### ISSUE TITLE
Q: will (sadly forced) migration from twistor/flysystem-guzzle require me to depend on the whole AWS SDK?

### ISSUE THREAD

**Issue by rulatir** [thephpleague/flysystem-aws-s3-v3#289]
I am forced to migrate away from an S3-over-twistor/flysystem-guzzle setup. One big advantage of that setup was that it just used a regular HTTP client to communicate with S3, and didn't require me to bring **THE SHEER VASTNESS OF ALL THE DOZENS OF MEGABYTES OF THE ENTIRETY OF THE AWS SDK** into my application.

Must that advantage definitely be lost if I migrate to flysystem-aws-s3-v3?

**Comment by frankdejonge** [comment]
You can always choose to maintain your own guzzle-only adapter.

**Comment by rulatir** [comment]
What is the answer to the yes/no question I posed?

**Comment by frankdejonge** [comment]
Word of advice, you need to work on your social skills. Issues with bold full caps stuff, pushing towards yes/no answers. You're pretty close to getting closed and blocked from raising new issues.

You can use league/flysystem-aws-s3-v3 which depends on the SDK, or you can use the async version which uses async-aws-sdk which doesn't depend on the SDK. For docs, see: https://flysystem.thephpleague.com/docs/adapter/async-aws-s3/
