### ISSUE TITLE
has() Method Throws Exception Rather than Returning False

### ISSUE THREAD

**Issue by bbatsche** [thephpleague/flysystem-aws-s3-v3#29]
Calling `has()` with an invalid file name is resulting in a S3Exception:

    Error executing "HeadObject" on "https://s3.amazonaws.com/[bucket-name]/[file-name]";
    AWS HTTP error: Client error: 403 (client): 403 Forbidden (Request-ID:[hex value])

Sample line of code (taken from a Laravel 5.1 Project)

```php
use Illuminate\Contracts\Filesystem\Cloud;

class S3Controller extends Controller
{
    protected $fs;

    public function __construct(Cloud $fs)
    {
        $this->fs = $fs;
    }
    public function getResource()
    {
        var_dump($this->fs->getDriver()->has('index.html')); // true
        var_dump($this->fs->getDriver()->has('index.htmll')); // Exception; expected false
    }
}
```

**Comment by frankdejonge** [comment]
@bbatsche which version of the adapter have you got installed? I thought this was fixed recently.

**Comment by bbatsche** [comment]
Requirement in `composer.json` is `"league/flysystem-aws-s3-v3": "~1.0"`. Version in `composer.lock` is `1.0.3`. I saw issue #13 which does look very similar, but seems to be focussed on just `404` errors. I'm getting a `403` (for a resource that is missing so that just seems wrong, but that's more Amazon's issue).

**Comment by frankdejonge** [comment]
@bbatsche it seems correct that this is throwing an exception then. This probably requires actions which flysystem can't provide. Have you looked into the reason of the 403 more?

**Comment by alesmana** [comment]
Similar issue happens in my local homestead development while my app running on Linode works fine.

After checking S3 permission, checked out old version, etc., this problem disappear when I restart homestead.

    homestead halt
    homestead up --provision

**Comment by bbatsche** [comment]
It looks like this was somehow related to my user's policies in AWS. Even thought I'd assigned what I *thought* were all the necessary read actions manually, going back and using Amazon's prebaked `AmazonS3ReadOnlyAccess` policy seems to have fixed this. For the record, here are the policies I created; any guidance on what I'd missed would be appreciated.

```json
{
    "Effect": "Allow",
    "Action": [
        "s3:GetBucketWebsite",
        "s3:GetObject",
        "s3:GetObjectAcl",
        "s3:GetObjectTorrent",
        "s3:GetObjectVersion",
        "s3:GetObjectVersionAcl",
        "s3:GetObjectVersionTorrent",
        "s3:ListBucket"
    ],
    "Resource": [
        "arn:aws:s3:::bucket-name",
        "arn:aws:s3:::bucket-name/*"
    ]
}
```

Regardless I'm going to close the issue as this is clearly my own error, not y'all's.

PS - Lord I hate Amazon's policy system.

**Comment by frankdejonge** [comment]
@bbatsche thanks for coming back and closing the issue :+1:
