### ISSUE TITLE
feof(): Argument #1 ($stream) must be of type resource, null given after upgrading to laravel 9 for files uploaded before the upgrade

### ISSUE THREAD

**Issue by ziming** [thephpleague/flysystem-aws-s3-v3#290]
Hi,

I originally posted this on spatie/medialibrary but thought I post it here too as I feel v3 of this library may be a possible cause since the upgrade from laravel 8 to laravel 9 also involves upgrading from v1 to v3 of this library

https://github.com/spatie/laravel-medialibrary/issues/2842

**Comment by frankdejonge** [comment]
I looked at the original issue, but I have no way to research or fix this. If you find out more info, that'd be great to share here.
