### ISSUE TITLE
Custom endpoint gives me a error

### ISSUE THREAD

**Issue by mmaaarten** [thephpleague/flysystem-aws-s3-v3#295]
Hey there,

when i fill in a custom endpoint i get the following error 
GuzzleHttp\Psr7\Exception\MalformedUriException
The path of a URI with an authority must start with a slash "/" or be empty

can someone help me out with this or fix this bug? cause when i just use s3 form aws without a endpoint its working fine.

**Comment by frankdejonge** [comment]
What do you mean by custom endpoint? Can you supply an example?

**Comment by mmaaarten** [comment]
Hey frank, when I enter an endpoint (so not the default endpoint from amazon) access key, secret, and bucketname I get the following The path of a URI with an authority must start with a slash "/" or be empty. When I remove the endpoint and I use the object storage of AWS instead of the one from idriveee2, for example, it works.
https://prnt.sc/RIR1SBqrDhKe

**Comment by frankdejonge** [comment]
Does the endpoint accept a trailing slash?

**Comment by mmaaarten** [comment]
I dont think so cause i get a timeout when i try that, i send a ticket to drive e2
