### ISSUE TITLE
Add support for AWS Pre-Signed url

### ISSUE THREAD

**Issue by Alg1d** [thephpleague/flysystem-aws-s3-v3#296]
Add ability to get the pre-signed URL to an Amazon S3 object by using the `Aws\S3\S3Client::createPresignedRequest()` method. More details can be found in [AWS documentation](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-presigned-url.html).

**Comment by maxhelias** [comment]
You already can do that, see https://github.com/thephpleague/flysystem-aws-s3-v3/pull/143 and https://github.com/sistemi-etime/flysystem-plugin-aws-s3-v3

**Comment by frankdejonge** [comment]
This functionality falls outside of the use-cases that Flysystem supports. We do not support one-off functionality as it breaks the value of an abstraction.

**Comment by Alg1d** [comment]
> You already can do that, see #143 and https://github.com/sistemi-etime/flysystem-plugin-aws-s3-v3

This plugin has not been updated since 2019 and does not work with the latest versions of the Flysystem

**Comment by frankdejonge** [comment]
You can use the AWS SDK directly to do this, no need to have flysystem in between.
