### ISSUE TITLE
UnableToWriteFile on Laravel 9

### ISSUE THREAD

**Issue by richoandika** [thephpleague/flysystem-aws-s3-v3#299]
Hello there,
I was upgrade the package, but I can't upload any file to my bucket even the system didn't hit my IAM.
I try to change the throw to enable in `config/filesystems.php`, The error returns `Unable to write file at location: xxx.jpg`
I don't know what happened, but if I try to upload file using `aws-cli` it's work nothing returns error or something wrong.
What's wrong with that? Can anyone help me?
and it's the package I used:
`laravel/framework: ^9.11`
`league/flysystem-aws-s3-v3: ^3.0`
These is the errors: https://flareapp.io/share/bP9O3xZ5
![image](https://user-images.githubusercontent.com/24300318/172621226-e1bab535-4829-4d80-bb4d-b89c7983bb37.png)

**Comment by richoandika** [comment]
@frankdejonge

**Comment by frankdejonge** [comment]
@richoandika don't ping

**Comment by frankdejonge** [comment]
@richoandika which exact version have you got installed of `league/flysystem-aws-s3-v3`?

**Comment by richoandika** [comment]
> @richoandika which exact version have you got installed of `league/flysystem-aws-s3-v3`?

@frankdejonge I was update the issue, I installed `^3.0` version, as in Laravel's documentation.

**Comment by frankdejonge** [comment]
@richoandika can you look in your lock file which exact version you have installed? The version you list is a range, the exact version is different.

**Comment by richoandika** [comment]
@frankdejonge I installed `3.0.0` version.
I don't know what happened, I tried use random [project](https://github.com/lunadiotic/laravel-s3) in Github with using my AIM key but got same errors.
![image](https://user-images.githubusercontent.com/24300318/172845642-18461e1d-f712-40fa-996b-6aa7e9d3ce6c.png)

**Comment by tomohirohiratsuka** [comment]
@richoandika 
Hi, I've faced issues like you and solved it by just removing `AWS_URL`,`AWS_ENDPOINT` from your `.env`.
The adaptor create URL properly even if you don't pass specific endpoint.
 It worked for me.

**Comment by mmehmet** [comment]
I have this exact same error - and removing `AWS_URL` or `AWS_ENDPOINT` does not fix anything

it seems to be something between Laravel 9 and this package though - as I _can_ get files to upload if I manually create a client using the `AwsS3V3Adapter`

@frankdejonge I know you have marked this as completed but it does seem to still be happening

I have:
`laravel/framework: v9.52.7
league/flysystem-aws-s3-v3: v3.15.0
aws/aws-sdk-php: v3.269.7`

I know a big (breaking) change between Laravel 8 and Laravel 9 is the way tokens are handled, as the AWS SDK introduced a change to tokens which L9 "fixes" but remains broken in L8

https://github.com/laravel/framework/issues/44977
https://github.com/aws/aws-sdk-php/issues/2567
https://github.com/aws/aws-sdk-php/pull/2517

not sure if this is related, but I am able to access other AWS services with Laravel façades (eg SQS and CloudWatch) which more directly use the AWS SDK - but not S3, which I believe their `Storage` façade wraps around the above filesystem adapter?

**Comment by frankdejonge** [comment]
@mmehmet I don't have enough information to investigate. If somebody wants to provide me a setup I can debug, I'll happily spend some time on it. However, I cannot reproduce this in my test suite and I'm not going to spend an unbounded amount of time until I magically find the problem and subsequent solution to this. I hope you understand, but ultimately that's how it's going to be.

**Comment by mmehmet** [comment]
I would just like to note the exact same thing is also happening when trying to access DynamoDB via the Cache façade - I have not yet tested it but I suspect, as with accessing S3, this problem is going to completely go away if I directly access DynamoDB via the AWS SDK, rather than via façades...

debug logging:
```
UnrecognizedClientException (client): The security token included in the request is invalid. - {
    "__type": "com.amazon.coral.service#UnrecognizedClientException",
    "message": "The security token included in the request is invalid."
} {"exception":"[object] (Aws\\DynamoDb\\Exception\\DynamoDbException(code: 0): Error executing \"PutItem\" on \"https://dynamodb.ap-southeast-2.amazonaws.com\"; AWS HTTP error: Client error: `POST https://dynamodb.ap-southeast-2.amazonaws.com` resulted in a `400 Bad Request` response:
{\"__type\":\"com.amazon.coral.service#UnrecognizedClientException\",\"message\":\"The security token included in the request i (truncated...)
UnrecognizedClientException (client): The security token included in the request is invalid. - {\"__type\":\"com.amazon.coral.service#UnrecognizedClientException\",\"message\":\"The security token included in the request is invalid.\"} at /var/task/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)
[stacktrace]
#0 /var/task/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\\WrappedHttpHandler->parseError()
#1 /var/task/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\\WrappedHttpHandler->Aws\\{closure}()
#2 /var/task/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\\Promise\\Promise::callHandler()
#3 /var/task/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /var/task/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\RejectedPromise::GuzzleHttp\\Promise\\{closure}()
#5 /var/task/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(159): GuzzleHttp\\Promise\\TaskQueue->run()
#6 /var/task/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(185): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#7 /var/task/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Handler\\CurlMultiHandler->execute()
#8 /var/task/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#9 /var/task/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#10 /var/task/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#11 /var/task/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#12 /var/task/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#13 /var/task/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#14 /var/task/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\\Promise\\Promise->wait()
#15 /var/task/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\\AwsClient->execute()
#16 /var/task/vendor/laravel/framework/src/Illuminate/Cache/DynamoDbStore.php(280): Aws\\AwsClient->__call()
#17 /var/task/vendor/laravel/framework/src/Illuminate/Cache/DynamoDbLock.php(38): Illuminate\\Cache\\DynamoDbStore->add()
#18 /var/task/vendor/laravel/framework/src/Illuminate/Cache/Lock.php(116): Illuminate\\Cache\\DynamoDbLock->acquire()

...
```
