### ISSUE TITLE
"Call to undefined method League\\Flysystem\\Filesystem::putFileAs()"

### ISSUE THREAD

**Issue by ristekbrin** [thephpleague/flysystem-aws-s3-v3#303]
i have an issue when i tried leage/flysystem-aws-s3-v3 3.0 on laravel 9 
i don't know what happen, i try everything configuration on filesystem on app and my service provider 
but still that issues on 
plis help

**Comment by frankdejonge** [comment]
That method does not exist. You should look at your stack trace, see where it is called and adjust the method call.

**Comment by frankdejonge** [comment]
Please open an issue with Laravel, this is not a Flysystem issue. Laravel is calling the wrong method, or you are calling the wrong laravel method.

**Comment by muradhajiyev** [comment]
@ristekbrin I'm facing same issue, Did you find solution?

**Comment by mostafaznv** [comment]
You should return an instance of FilesystemAdapter

check this example:
https://laravel.com/docs/9.x/filesystem#custom-filesystems
