### ISSUE TITLE
League\Flysystem\FileNotFoundException for existing files

### ISSUE THREAD

**Issue by Artem-Schander** [thephpleague/flysystem-aws-s3-v3#306]
Sometimes I get said exception regardless of the files being accessible.
The only thing that helps is to clear the cache `php artisan cache:clear`.
This is extremely annoying for my customers, since they need to notice it and to inform me to get access to their files.
I there anything I can do to avoid this? 

I'm using `league/flysystem-aws-s3-v3:^1`

**Comment by frankdejonge** [comment]
If the Laravel cache reset fixes it, I don’t see how that is a Flysystem issue.

**Comment by Artem-Schander** [comment]
Ok. Sorry for the noise then. What would you suggest? Ticket at laravel?

**Comment by frankdejonge** [comment]
That sounds like a good idea 👍
