### ISSUE TITLE
Laravel 9.x

### ISSUE THREAD

**Issue by GlauberF** [thephpleague/flysystem-aws-s3-v3#307]
I'm studying to use it with laravel 9.x but the analyzer told me that it is not compatible, could you tell me if you are studying any updates?

![Captura de Tela_selecionar área_20220831115943](https://user-images.githubusercontent.com/11314585/187709845-9e35c1fb-d133-4aaa-82d4-16efad9d7124.png)

https://laravelshift.com/can-i-upgrade-laravel/league/flysystem-aws-s3-v3

**Comment by frankdejonge** [comment]
Laravel shift is wrong, just try to install it.

**Comment by GlauberF** [comment]
ok, thanks!

**Comment by jasonmccreary** [comment]
This is likely due to the recent rename of the "vendor" from _league_ to _thephpleague_. As @frankdejonge, this package does work, [Shift](https://laravelshift.com/) may just be looking for the recent version under the old name on Packagist.

**Comment by frankdejonge** [comment]
@jasonmccreary for your investigation; the vendor hasn’t changed since the initial release.

**Comment by jasonmccreary** [comment]
Gotcha. Not _rename_ then so much as the package name and repo name do not match. That's what was throwing off Shift. This is [now showing the latest versions](https://laravelshift.com/can-i-upgrade-laravel/league/flysystem-aws-s3-v3). However, I expect Laravel 9.x requires a minimum of 3.0. So I'll need to see why that's off.

But at least it show as "compatible" now. 👍

**Comment by frankdejonge** [comment]
@jasonmccreary could it be a change in branch names? The repository was always like that, so I’d expect this to have been a problem before too. Does that make sense?

**Comment by GlauberF** [comment]
@frankdejonge 
so i'm installing on laravel 8.x and PHP 8.1.9 and i'm getting the following error:

```
composer require league/flysystem-aws-s3-v3
Using version ^3.2 for league/flysystem-aws-s3-v3
./composer.json has been updated
Running composer update league/flysystem-aws-s3-v3
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires league/flysystem-aws-s3-v3 ^3.2 -> satisfiable by league/flysystem-aws-s3-v3[3.2.0].
    - league/flysystem-aws-s3-v3 3.2.0 requires league/flysystem ^3.0.0 -> found league/flysystem[3.0.0, ..., 3.2.1] but the package is fixed to 1.1.9 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require league/flysystem-aws-s3-v3:*" to figure out if any version is installable, or "composer require league/flysystem-aws-s3-v3:^2.1" if you know which you need.

```

**Comment by frankdejonge** [comment]
You can install it using: composer require league/flysystem-aws-s3-v3:^1.1

**Comment by GlauberF** [comment]
![Captura de Tela_selecionar área_20220905103439](https://user-images.githubusercontent.com/11314585/188460853-62e56639-2a49-4bca-8595-9aabd9066220.png)
