### ISSUE TITLE
Does not support reduced redundancy storage or other constructor options

### ISSUE THREAD

**Issue by cweagans** [thephpleague/flysystem-aws-s3-v3#31]
The v2 adapter supports setting various S3 options in the adapter constructor. The v3 adapter does not, which means that (unless I'm missing something) reduced redundancy storage isn't supported. Any plans to add this functionality?

**Comment by Tewki** [comment]
Sorry for the bump but someone else might need it; In the upload options/config, 
```PHP
StorageClass => REDUCED_REDUNDANCY
```

**Comment by frankdejonge** [comment]
The storage class option is supported in the options array.
