### ISSUE TITLE
Using Storage::exists() always return TRUE but have not files on S3

### ISSUE THREAD

**Issue by cuongdvscuti** [thephpleague/flysystem-aws-s3-v3#312]
I got issue when try to check exists file on S3 
` Storage::exists("<path to file>")`

In `path to file` enter to Storage::exists() I was enter random text but still return TRUE any time 

Please help me check this issue. Thank 

Note: I'm using league/flysystem-aws-s3-v3": "^1.0

**Comment by gdebrauwer** [comment]
I'm having the same issue

**Comment by bcartfall** [comment]
I'm having the same issue as well (v3.12.1). Also had the same issue back in November 2022.

Downgrading to `v3.10.3` resolves the issue.

**Comment by frankdejonge** [comment]
Version 3.12.1 should fix this for you.

**Comment by frankdejonge** [comment]
@bcartfall what S3 vendor are you using?

**Comment by bcartfall** [comment]
@frankdejonge I am using Amazon S3 with the following configuration (`filesystems.php`):

```
's3' => [
    'driver' => 's3',
    'key' => '...',
    'secret' => '...',
    'region' => 'us-west-2',
    'bucket' => '...',
    'options' => [
        'ServerSideEncryption' => 'AES256',
        'StorageClass' => 'INTELLIGENT_TIERING',
    ],
],
```
Note that if I remove `options` key from the configuration `Storage::exists()` works as expected in `v3.12.1`.

**Comment by cuongdvscuti** [comment]
thanks you. I solved the problem by upgrading

aws/aws-sdk-php -> 3.252.3
league/flysystem-aws-s3-v3 -> 1.0.30
