### ISSUE TITLE
Critical: I am getting exception error when trying to get image url from s3 bucket

### ISSUE THREAD

**Issue by sanjay-vv** [thephpleague/flysystem-aws-s3-v3#313]
Whenever i am calling "Getobject" method to get image url from s3 bucket then am getting a error "trying to access array offset on value of type null in file RetryableMiddleware.php"

When i tried to find solution  on google it giving me that change in package core file RetryableMiddleware.php but i don't want to touch core files.

so please suggest me how i can solve this issue.

**Comment by frankdejonge** [comment]
@sanjay-vv please raise this issue with the S3 repository.

**Comment by sanjay-vv** [comment]
@frankdejonge  can you please give me the url of that repository.
