### ISSUE TITLE
Duplicating URL path

### ISSUE THREAD

**Issue by yurih567** [thephpleague/flysystem-aws-s3-v3#325]
When using a custom path, the endpoint is becoming duplicated

ENVs:
endpoint = "https://br-ne-1.api.{custom domain}.cloud/domainobjects"
use_path_style_endpoint = true

Generated url: "https://br-ne-1.api.{custom domain}.cloud/domainobjects/domainobjects/{bucket name}/images/customers/image.png"

The path "domainobjects" is duplicated.

**Comment by frankdejonge** [comment]
Seems like an AWS issue, not a Flysystem issue.
