### ISSUE TITLE
Potential URI resolution path traversal in the AWS SDK for PHP

### ISSUE THREAD

**Issue by vincent-goossens** [thephpleague/flysystem-aws-s3-v3#326]
The package aws/aws-sdk-php needs to be updated >= 3.288.1.

https://github.com/thephpleague/flysystem-aws-s3-v3/blob/3.x/composer.json#L15C25-L15C25

**aws/aws-sdk-php**
https://github.com/aws/aws-sdk-php/security/advisories/GHSA-557v-xcg6-rm5m

**Comment by soulseekah** [comment]
Quick fix would be to `composer require aws/aws-sdk-php:^3.288.1`

**Comment by frankdejonge** [comment]
Just FYI, this library doesn't _need_ to be fixed for users to fix their security issue.

**Comment by vincent-goossens** [comment]
@frankdejonge 
This library on current version 3.x is using including the package ["aws/aws-sdk-php": "^3.220.0"](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/3.x/composer.json#L15) that have issued a security update for all versions bellow 3.288.1 (https://github.com/aws/aws-sdk-php/security/advisories/GHSA-557v-xcg6-rm5m ).

This has not to be with the users security issue but this package security issue.

has @soulseekah mentioned to avoid this security issue on this library os to update the aws/aws-sdk-php to >= 3.288.1 has the library self announced.

**Comment by frankdejonge** [comment]
@vincent-goossens sorry vincent, but you're wrong. Although this package doesn't prevent the affected package to be installed, you yourself can just run a compose update and get the patched version.
