### ISSUE TITLE
has() always returns false for directories

### ISSUE THREAD

**Issue by phazei** [thephpleague/flysystem-aws-s3-v3#33]
When trying to getMetaData on directory it always returns false, at least for directories in the root folder, haven't tested others.

If I have a directory named "folder" and I do `$adapter->has("folder")` it returns false.  OTOH, if I do `$adapter->has("folder/")` with that trailing slash, it properly returns the meta data.

The problem with that in Filesystem, the [has method](https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L67) calls `Util::normalizePath($path)` which strips a trailing slash.  And even if it didn't, it seems most of the utilities that use Flysystem never send it to that with the trailing slash anyway.

I think the issue lies with S3, it shouldn't need the trailing slash, and the other drivers don't expect one either.

Only way I can see fixing it is attempting as file first, and if that's false, try again with a trailing slash.  I'm not sure of anything better.

**Comment by frankdejonge** [comment]
Folders are second class citizens in Flysystem, they're less important than files. They'll be implicitly created when writing to a directory, therefor has calls should only be done on files.
