### ISSUE TITLE
Setting content-encoding header

### ISSUE THREAD

**Issue by luukholleman** [thephpleague/flysystem-aws-s3-v3#39]
I've got an issue in laravel with pushing files' metadata to s3, when I execute the following code:

    \Storage::disk('s3')->getDriver()->put('image/'.$name, gzencode(file_get_contents($this->path)), ['ContentEncoding' => 'gzip', 'ContentType' => 'image/jpeg']);

And look in s3 to see what metadata is stored, I only see the Content-Type header. The same for:

    \Storage::disk('s3')->getDriver()->put('file/'.$name, gzencode(file_get_contents($this->path)), ['ContentEncoding' => 'gzip', 'ContentType' => 'application/octet-steam', 'ContentDisposition' => 'attachment']);

Content encoding and content disposition are nowhere to be found, I can however set them manually and then the file decompresses/downloads as expected.

**Comment by mjanda** [comment]
First, compressing JPEG image is unnecessary (you won't get smaller size and it will take more time to decompress on client).

But to solve your issue, I was able to set gzip headers on S3 this way (change their values as well as ACL and removev StorageClass if needed)
```
Storage::disk('s3')->getDriver()->getAdapter()->getClient()->upload(
    env('S3_BUCKET'),
    $s3_filename,
    $gzdata,
    'public-read',
    ['params' => [
        'ContentType' => 'application/json',
        'ContentEncoding' => 'gzip',
        'StorageClass' => 'REDUCED_REDUNDANCY',
    ]
]);
```

**Comment by frankdejonge** [comment]
The ContentEncoding settings has been added to the metadata list and will now be properly forwarded.
