### ISSUE TITLE
maybe use aws-sdk multipartUpload

### ISSUE THREAD

**Issue by svycka** [thephpleague/flysystem-aws-s3-v3#41]
http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multipart-upload.html
> Multipart uploads are designed to improve the upload experience for larger objects. With it you can upload objects in parts that can be uploaded independently, in any order, and in parallel. You can use a multipart upload for objects from 5 MB to 5 TB in size.
> 
> Amazon S3 customers are encouraged to use multipart uploads for objects greater than 100 MB.

**Comment by frankdejonge** [comment]
@svycka the sdk does this internally by default, the default threshold is `16777216` bytes (16MB) and when uploading a larger file will use 3 concurrent uploads.
