### ISSUE TITLE
Leak on write & writeStream

### ISSUE THREAD

**Issue by sirprize** [thephpleague/flysystem-aws-s3-v3#44]
Hi, after upgrading to version 1.0.0 memory usage is increasing with every write. Same was true with version 0.4 but `$filesystem->getCache()->delete($key);` solved the issue...

    use Aws\S3\S3Client;
    use League\Flysystem\AwsS3v3\AwsS3Adapter as S3Adapter;
    use League\Flysystem\Filesystem;

    $s3 = new S3Client([
        'credentials' => array(
            'key' => '<key>',
            'secret' => <secret>
        ),
        'region' => 'us-east-1',
        'version' => '2006-03-01'
    ]);

    $s3Adapter = new S3Adapter($s3, '<bucket>', '');
    $filesystem = new Filesystem($s3Adapter);

    for ($x = 0; $x < 10; $x++)
    {
        $file = 'image.jpg';
        $key = sprintf('testing/%s', uniqid());

        $stream = fopen($file, 'r+');
        $filesystem->writeStream($key, $stream);

        if (is_resource($stream))
        {
            fclose($stream);
        }

        echo sprintf("Memory: %s M\n", round(memory_get_usage() / 1024 / 1024, 2));
    }

Memory: 4.02 M
Memory: 4.16 M
Memory: 4.3 M
Memory: 4.45 M
Memory: 4.59 M
Memory: 4.74 M
Memory: 4.88 M
Memory: 5.02 M
Memory: 5.17 M
Memory: 5.31 M

**Comment by sirprize** [comment]
This issue appears not to be Flysystem-related. Also happens when using `Aws\S3\S3Client::putObject()` directly...

**Comment by frankdejonge** [comment]
@sirprize thanks for coming back and closing the issue!

**Comment by sirprize** [comment]
@frankdejonge Thank you for this great library! Investigating further and came across this: https://github.com/guzzle/guzzle/issues/813
