### ISSUE TITLE
Duplicate directories with listContents

### ISSUE THREAD

**Issue by MichaelMackus** [thephpleague/flysystem-aws-s3-v3#45]
For some reason, the aws s3 adapter is giving me duplicate directories when I use the `listContents` function (only with a blank first arg - I'm trying to crawl the root dir).

When debugging I noticed when I step into the `Util::emulateDirectories` function, the `$listing` variable already has the directories declared. Which leads me to believe that maybe the `Util::emulateDirectories` call is unnecessary for the root directory?

**Comment by frankdejonge** [comment]
This was actually a but in the Util::emulateDirectories function, which has been solved and tagged as flysystem version `1.0.15`.

**Comment by MichaelMackus** [comment]
:+1: thanks! :)
