### ISSUE TITLE
Support for "Website Redirect Location"

### ISSUE THREAD

**Issue by ZiadHilal** [thephpleague/flysystem-aws-s3-v3#50]
Trying to figure out how to add the "Website Redirect Location" option, doesn't look like it's supported. You can read more on the subject here:

http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

Basically, it's a way to set a redirect on an object if your S3 bucket is configured as a static website. 

Looking at this code here:
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L590

Looks like it's looping through $metaOptions, but doesn't have an option for "Website Redirect Location".

**Comment by aarondfrancis** [comment]
Opened a PR: https://github.com/thephpleague/flysystem-aws-s3-v3/pull/66

**Comment by frankdejonge** [comment]
Closing this because the PR was merged.
