### ISSUE TITLE
MIME type detection when body is a stream

### ISSUE THREAD

**Issue by ukautz** [thephpleague/flysystem-aws-s3-v3#54]
The `upload` method tries to [detect the MIME type](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L554) only if the body is a string. In case it's a stream no fallback detection via (file) extension is tried.

I could submit a PR if you like. Or is there a reason which I don't see that no fallback is tried?

**Comment by frankdejonge** [comment]
@ukautz a PR would be very welcome! :+1:

**Comment by frankdejonge** [comment]
This is fixed in the main repo now.
