### ISSUE TITLE
Double Util::normalizePath with Filesystem->assertPresent results in FileNotFoundException

### ISSUE THREAD

**Issue by dazzy** [thephpleague/flysystem-aws-s3-v3#56]
league/flysystem 1.0.18
league/flysystem-aws-s3-v3 1.0.9

`$filesystem->read('something/id_33_49612.jpg')` and `$filesystem->delete('something/id_33_49612.jpg')`
throws FileNotFoundException. Probably many more methods, but these are the ones I tested.

I traced this back to `Filesystem->assertPresent()`, and solved the issue for me by changing line 380 from `if ( ! $this->has($path)) {` to `if ( ! $this->getAdapter()->has($path)) {`.

The issue seem to be a case of double `Util::normalizePath()` as all functions in Filesystem that calls `assertPresent()` has already done `Util::normalizePath()`.

I don't know if this should be filed in "Flysystem" or here as I have not tested enough. It is either an issue with the adapter or an issue with `Filesystem`.

**Comment by frankdejonge** [comment]
@dazzy Hi, I've just added a test case to check if double path normalisation has side-effects, all the tests still pass so my guess is that it's something else. Have you got any more clues?

**Comment by dazzy** [comment]
Thank you for the quick response. I tested some more, and I think I found the error. It was my mistake; I was extending the class and Filesystem's `has()` became my `has()` and even if it shouldn't have garbled the path, it did. Sorry.

**Comment by frankdejonge** [comment]
@dazzy no worries, thanks for coming back and closing the issue. Glad you found the error.
