### ISSUE TITLE
set default Config to null in write/update/upload/copy

### ISSUE THREAD

**Issue by tsalufe** [thephpleague/flysystem-aws-s3-v3#57]
$options is not required in S3ClientTrait. [https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3ClientTrait.php](url)

So should be Config. So that I don't have to construct an empty Config: new \League\Flysystem\Config([]).

Most of time, I only need to employ default/existing logic of upload().

**Comment by frankdejonge** [comment]
@tsalufe I don't really understand what you mean. We don't use the trait and we always supply options, besides that the adapter doesn't instantiate a Config object and the AWS SDK doesn't know about our config object.

**Comment by tsalufe** [comment]
Hi frankdejonge, S3ClientTrait is implemented by S3Client which you use to execute commands. The options S3Adapter passes to S3Client is from Config. But in S3Client(or S3ClientTrait to be exact) doesn't require options, which by default is empty array.

In my case, I have a lot of files, I don't set configs for individual file. Permissions are set at bucket level. File size, content type can be set by your code in upload(). Therefore, I don't need to customize Config to pass to S3Adapter. But I have to attach an empty Config object to write() even the Config doesn't have any data.

**Comment by frankdejonge** [comment]
@tsalufe I think you forgot to wrap the adapter in a filesystem instance. You should use it like this:

```php
$adapter = new AwsS3Adapter($client, 'your-bucket-name');
$filesystem = new Filesystem($adapter);
```

I've updated the readme.

**Comment by frankdejonge** [comment]
The adapters should never be used directly.

**Comment by tsalufe** [comment]
Good point. Thanks.
