### ISSUE TITLE
Does not support InstanceRoles when cached.

### ISSUE THREAD

**Issue by monk-ee** [thephpleague/flysystem-aws-s3-v3#60]
When you run php artisan config:cache the config cache populates with:
 array (
        'driver' => 's3',
        'key' => '',
        'secret' => '',
        'region' => 'ap-southeast-2',
        'bucket' => 'mybucket',
      ),

The instance role temporary credentials do not get found and the filesystem fails back to the default.

I have tried setting -
S3_ACCESS_KEY=
S3_SECRET_KEY=
and
S3_ACCESS_KEY=null
S3_SECRET_KEY=null

But neither options work.

If the cache is not compiled - then the filesystem plugin works perfectly.

**Comment by frankdejonge** [comment]
@monk-ee could it be that this is an issue with @laravel rather than Flysystem?

**Comment by monk-ee** [comment]
Ok I  guess so, it seemed to me that it could be lower down the stack, but it does mean your plugin fails for this use case

**Comment by frankdejonge** [comment]
@monk-ee I'm not sure which use-case you are describing here. It seems to me the config is somehow wrongly persisted and then passed to the S3Client. I don't believe flysystem can do anything about that. But I might be missing something.
