### ISSUE TITLE
`rewind(): stream does not support seeking` error

### ISSUE THREAD

**Issue by jackmu95** [thephpleague/flysystem-aws-s3-v3#65]
After a4d729864269e57dcde05c771beb640e85653d8b I get this `rewind(): stream does not support seeking` error when using [Glide](https://github.com/thephpleague/glide) in combination with Laravel.
 
I'am not sure if the error is related to Glide because it's using `rewind()` [here](https://github.com/thephpleague/glide/blob/0dd3e4ec976ab7a38fc42196d03014f9fb82cc94/src/Server.php#L442) or if the newest changes made in the commit mentioned above create some compatibility issues with other libraries in general.

**Comment by frankdejonge** [comment]
@reinink hey bro! The above should be interesting for you. Basically the rewind should only be done if `ftell` returns `!= 0`.

**Comment by jackmu95** [comment]
@frankdejonge Thanks a lot. I create a [pull request](https://github.com/thephpleague/glide/pull/137) on the Glide project to check if the stream is seekable before using `rewind()`.
