### ISSUE TITLE
ContentLength detection when body is a remote stream

### ISSUE THREAD

**Issue by basz** [thephpleague/flysystem-aws-s3-v3#69]
[1.0.12](https://github.com/thephpleague/flysystem-aws-s3-v3/compare/1.0.11...1.0.12) introduced an issue with remote streams. As streams are not downloaded anymore [fstat()](http://php.net/manual/en/function.fstat.php) cannot get the file size. Therefore in the upload method $options['ContentLength'] might become NULL and the aws idk will throw an exception.

```
if ( ! isset($options['ContentLength'])) {
    $options['ContentLength'] = is_string($body) ? Util::contentSize($body) : Util::getStreamSize($body);
}
```
A validator within the aws sdk throws an exception
```
Found 1 error while validating the input provided for the PutObject operation: [ContentLength] must be numeric. Found NULL
```

I found that simply unsetting $options['ContentLength'] when its value NULL resolves this issue but I am wondering if any other solutions might be preferred.

**Comment by frankdejonge** [comment]
@basz So this would be the case when a readStream is opened, and then used as a writeStream later on without fully downloading it in the middle?

**Comment by basz** [comment]
yes, I use the mount manager to copy a file from one s3 bucket to another...

**Comment by frankdejonge** [comment]
@basz just pushed a commit to master, could you check that out? I'm going to bed pretty soon, will check back tomorrow.

**Comment by frankdejonge** [comment]
@basz I've tested this and it resolved the exception being thrown. I've tagged 1.0.13.

**Comment by basz** [comment]
tested and it works... thanks a mil
