### ISSUE TITLE
Consider adding support for using credential profile?

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem-aws-s3-v3#7]
http://docs.aws.amazon.com/aws-sdk-php/guide/latest/credentials.html#credential-profiles

Looks like this is a better way to store and use AWS access keys?

**Comment by frankdejonge** [comment]
This is not up to this package, how you construct the S3Client is entirely up to the user. Flysystem doesn't make any assumptions about this, so this is possible as is :+1:

**Comment by Prendo93** [comment]
Sorry to chime in on an old issue @frankdejonge , but I'm having a hard time figuring out how to do this. (I assume tho same process will work for IAM Roles). Is in possible to point me to a code snippet of how to construct the s3Client with empty credentials - which I understand will read credentials from a profile or IAM role - so I don't have to add my credentials to the .env file.

**Comment by frankdejonge** [comment]
@Prendo93 the code samples are on the link posted in the issue description.
