### ISSUE TITLE
Support for seekable streams

### ISSUE THREAD

**Issue by pavankumarkatakam** [thephpleague/flysystem-aws-s3-v3#70]
As mentioned in the docs, stream is not seekable by default, we need to pass an option to it 
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-stream-wrapper.html#opening-seekable-streams, from your code when we call `readStream()` we are getting the stream response but with `seekable:false` , so this is a feature request to add options for `readStream` to get the seekable working.

**Comment by frankdejonge** [comment]
This has been fixed in #74
