### ISSUE TITLE
Errors with large file upload

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/flysystem-aws-s3-v3#71]
I am attempting to do a large file upload using this adapter.

The file, which is 3gb in size, got to the end of the upload (I'm using elFinder) and then tried to finalise (I assume)

The last request took just under 10 minutes until it returned the follow error:

> "An exception occurred while uploading parts to a multipart upload. The following parts had errors:↵- Part 399: Error executing &quot;UploadPart&quot; on &quot;https://s3-eu-west-1.amazonaws.com/<BUCKET-NAME>/my_file.extensions?partNumber=399&amp;uploadId=XOexCw.alF7DPdFpIt1psnh_kshFBHFt_bxBaOFgSoBStZ9elfKQqLVt4FlNG_b_0kgAd5B7z6ejraLZ5qe_Bw--&quot;; AWS HTTP error: cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  (server): 100 Continue - ↵"

I have tried with very small files, and they upload fine, so I assume the implementation is sound.

Any ideas?

**Comment by frankdejonge** [comment]
@paulcanning looks like it's a problem outside of Flysystem's scope. Have you verified that your openssl php extension is installed?

**Comment by paulcanning** [comment]
Hmm, it doesn't seem to be enabled. However, I don't want to use SSL... is that an issue?

And why would small files work, but not large ones? The only difference is the size...

**Comment by frankdejonge** [comment]
@paulcanning you can disable ssl in the sdk: https://docs.aws.amazon.com/aws-sdk-php/v3/guide/faq.html#how-do-i-disable-ssl

**Comment by frankdejonge** [comment]
@paulcanning before disabling SSL I'd definitely consult with business people to see if that's a problem, because in some organisations this can have serious impact.

**Comment by paulcanning** [comment]
Yea, I understand the issues with not using SSL.

Do you know where I can find information on using SSL with the AWS S3 PHP SDK?

I'm just testing a 1GB upload now without SSL, see how that goes.

**Comment by frankdejonge** [comment]
@paulcanning I sent the link in the previous comment. Also, because this is not an issue for flysystem I'm closing the issue. Feel free to comment afterwards.
