### ISSUE TITLE
Empty result when trying to read file contents

### ISSUE THREAD

**Issue by louiscoetzee** [thephpleague/flysystem-aws-s3-v3#76]
I am trying to read the contents of a file called schema.xml, the file does exist and I am 100% sure my path is correct. The $schema_exists variable does return true. It seems that all functions on AWS is working except for the read function. I am getting an empty result. Btw. I did check, my schema.xml files do have contents. Any help will be appreciated.  

`
$client = S3Client::factory([
      'credentials' => [
          'key'    => 'my-key',
          'secret' => 'my-secret',
      ],
      'region' => 'us-west-2',
      'version' => 'latest',
  ]);

  $adapter = new AwsS3Adapter($client, 'assetlibrary');

  $filesystem = new League\Flysystem\Filesystem($adapter);

  $toolkits = $filesystem->listContents('toolkits');

  foreach ($toolkits as $key => $toolkit) {
    $toolkit_name = $toolkit['basename'];

```
if ($toolkit['type'] == 'dir')
{
  $toolkit_path = 'toolkits/'.$toolkit_name.'/';
  $schema_file = $toolkit_path.'schema.xml';
  $schema_exists = $filesystem->has($schema_file);

  if ($schema_exists)
  {
    $contents = $filesystem->read($schema_file);

    echo $contents;
  }
```

`

**Comment by dargue3** [comment]
did you ever figure this out? suffering from a similar problem right now.

**Comment by frankdejonge** [comment]
@dargue3 any chance you can debug one of those calls? Could be a configuration issue of some sorts.

**Comment by dargue3** [comment]
Hey @frankdejonge, you can get slightly more information about my problem on [my StackOverflow question](http://stackoverflow.com/questions/40642842/storageget-using-amazon-s3-returns-false).

I'm using flysystem-aws as a plugin for Laravel. I am able to `put()`, `getMetaData()`, `exists()`, everything works as it should, simply the `read()` and `get()` commands always return `false`.

**Comment by jonathanpmartins** [comment]
@dargue3 

After digger deeper into the code I found this message

```
"Error executing "GetObject" on "file"; AWS HTTP error: file_exists(): open_basedir restriction in effect. File(/etc/pki/tls/certs/ca-bundle.crt) is not within the allowed path(s): (paths)"
```
First it seems that my server don't have this file, but it have! The file is located in another folder.
```
/etc/ssl/certs/ca-certificates.crt
```
So, to solve my problem in Ubuntu I have to create this folder ``/etc/pki/tls/certs`` and after that, symlink to the correct file:
```
cd /etc/pki/tls/certs;
sudo ln -s /etc/ssl/certs/ca-certificates.crt ca-bundle.crt;
```
Edit your ``php.ini`` and add ``/etc/pki/tls/certs/ca-bundle.crt`` to the ``open_basedir`` configuration.

Restart your php server!

For me it solves the problem, hope it helps!

**Comment by frankdejonge** [comment]
Seems to be solved on stackoverflow.
