### ISSUE TITLE
s3 URL using old format (Ordinary Calling Format) 

### ISSUE THREAD

**Issue by miscbits** [thephpleague/flysystem-aws-s3-v3#77]
We have a bucket thats url is https://s3.amazonaws.com/ourbucketname

Amazon at some point switched this to create a url that looks like https://s3.ourbucketname.amazonaws.com which is causing an error when we try to upload a file 
  [GuzzleHttp\Exception\ConnectException]
  cURL error 6: Could not resolve host: s3.healthjump.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Is there a way to set the calling format to use the old url structure rather than the new one? 

I know in other libraries for other languages (like python) this is possible. 
https://gist.github.com/garnaat/2938586

So I was wondering if this functionality existed here or if we had to potentially extend that.

**Comment by codebykyle** [comment]
+1 on this.

Using the default config I get:
`Error executing "ListObjects" on "https://s3.amazonaws.com/test-bucket?prefix=&encoding-type=url"; AWS HTTP error: cURL error 6: Could not resolve host: s3.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Looking further into it, that bucket URL does not work. However,
`https://test-bucket.s3.amazonaws.com/?prefix=&encoding-type=url`

works fine and properly lists out the files.

I believe this is the same issue?

**Comment by miscbits** [comment]
Yes this is the same issue. The term OrdinaryCallingFormat comes from boto (a Python s3 library) though I think its also a term used in the s3 documentation.

**Comment by codebykyle** [comment]
What exactly happened here to create the different URL structure? I'm relatively new to S3. I've created a new bucket with default options and that is the URL that is produced. I'm not able to use filesystem or flysystem with this URL structure which appears to be the default for my account. Am I missing something?

**Comment by miscbits** [comment]
Amazon just updated your URL structure to access S3 buckets. The new structure uses bucket.s3-aws-region.amazonaws.com, but this means if your bucket name has `.` characters then the regular format won't work and you have to use the old system which is still supported but not recommended by Amazon. The old format is s3-aws-region.amazonaws.com/bucket

If you don't have a dot in your bucket name, your issue might be with your region not being specified. Make sure in your .env file you have 
```
AWS_ACCESS_KEY_ID="YOUR ACCESS KEY"
AWS_SECRET_ACCESS_ID="YOUR SECRET KEY"
AWS_BUCKET="YOUR BUCKET NAME"
AWS_REGION="YOUR REGION"
```
example region = "us-west-2"

This information is used in config/filesystem at the bottom. 
```
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID', ''),
            'secret' => env('AWS_SECRET_ACCESS_ID', ''),
            'region' => env('AWS_REGION', ''),
            'bucket' => env('AWS_BUCKET', ''),
        ],
```

If that works for you that's good. If you do have a dot in your bucket name the other solution might just be changing the name. The company I work for cannot do that because we have dependencies on the bucket and if we changed the name we would anger clients so it would be more useful if there were just a config option. Because this question has been ignored I can only assume that there is no option like this.

**Comment by codebykyle** [comment]
No dot in the bucket name. The region is us-east-1 which just produces a URL without the region. 

Regarding your question with custom bucket endpoints, I'm reading through this and there are a few configuration options you can set which might work.

`
        // Use the bucket style middleware when using a "bucket_endpoint" (for cnames)
        if ($this->getConfig('bucket_endpoint')) {
            $stack->appendBuild(BucketEndpointMiddleware::wrap(), 's3.bucket_endpoint');
        }
`


`bucket_endpoint` is a boolean with the description:
`
            'bucket_endpoint' => [
                'type'    => 'config',
                'valid'   => ['bool'],
                'doc'     => 'Set to true to send requests to a hardcoded '
                    . 'bucket endpoint rather than create an endpoint as a '
                    . 'result of injecting the bucket into the URL. This '
                    . 'option is useful for interacting with CNAME endpoints.',
            ],`


Set the following config in the filesystems file:
`
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION', 'us-east-1'),
            'bucket' => env('AWS_BUCKET', 'bucketname'),
            'bucket_endpoint' => true,
            'endpoint' => 'yourendpointhere'
        ],`

Maybe this will help? This did not solve my issue, but perhaps yours?

**Comment by codebykyle** [comment]
Some additional information. That _did_ change the URL structure in the request. However, I still get the same error.

![image](https://cloud.githubusercontent.com/assets/26160129/24232133/6329d792-0fbb-11e7-98d3-0d0dcfb3c538.png)

Requesting the exact same URL via Postman using AWS Signature authentication, I'm able to properly retrieve the bucket.

![image](https://cloud.githubusercontent.com/assets/26160129/24232167/9e9a84b6-0fbb-11e7-96bc-12e1171c1b4f.png)

**Comment by codebykyle** [comment]
Oh man! Finally figured it out. After spending two days digging through the source code of this package and the AWS S3Client, setting hundreds of breakpoints trying to find out why the exact same request would work from my host machine using Postman, but not from the Flysystem Adapter, a solution was found.

The issue is I work in Homestead. Recently there was a bad update pushed out by Canonical, who maintains Ubuntu, which broke DNS resolution after a few hours.

This is known as the "2017 ubuntu DNS resolution issue" and would result in host resolution errors.

To fix it:
```
sudo apt-get update
sudo apt-get upgrade
```

Then run:
`sudo dpkg -l | grep "GNU C Library" | awk '{print $3}'`


Ubuntu 16.X should be similar to:
```
2.23-0ubuntu7
2.23-0ubuntu7
2.23-0ubuntu7
```

Ubuntu 14.X:
```
2.19-0ubuntu6.11
2.19-0ubuntu6.11
```

and Ubuntu 12.X:
```
2.15-0ubuntu10.17
2.15-0ubuntu10.17
```

Source: 
https://www.digitalocean.com/community/questions/how-to-fix-the-march-2017-ubuntu-dns-resolution-issues
https://forums.aws.amazon.com/thread.jspa?threadID=251956&tstart=0

**Comment by miscbits** [comment]
Oh wow that is a pretty crazy error! And yeah I think that might do the trick. I'll try it later and let you know. If it works I suppose I can just close this ticket too.

**Comment by miscbits** [comment]
That solved our issue.
