### ISSUE TITLE
Setting base_url in Laravel implementation

### ISSUE THREAD

**Issue by beniaminorossini** [thephpleague/flysystem-aws-s3-v3#78]
I need to use s3 adapter with service that are not Amazon, so i need to change base_url property during initialization.
Where i can accomplish that in a very basic Laravel installation?
Setting base_url in config/filesystem don't make any effect (it is ignored). 
Should i override s3 factory method? But where in Laravel? I need to implement my own service provider to initialize s3 adapter?
Thx a lot for any clues.

**Comment by frankdejonge** [comment]
This issue should be posted on the laravel repository. More info on this subject can be found here: https://www.jernejsila.com/2014/09/10/add-dropbox-filesystem-driver-laravel-5-project/
