### ISSUE TITLE
Annotation error : @http in method Aws\AwsClientInterface::getCommand()

### ISSUE THREAD

**Issue by GCalmels** [thephpleague/flysystem-aws-s3-v3#87]
Hey,

I have this error :
The annotation "@http" in method Aws\AwsClientInterface::getCommand() was never imported.
when I try to use S3.
Symfony thinks that "@http" is an annotation, is it possible to do otherwise?
I tried aws-sdk-php-symfony without any more success

Thanks

**Comment by frankdejonge** [comment]
@GCalmels this looks like it's not related to flysystem. I'd open up an issue with the annotation package vendor or the corresponding symfony bundle.

**Comment by GCalmels** [comment]
Ok, thank you!
