### ISSUE TITLE
Access methods never return when given path to non-existent file

### ISSUE THREAD

**Issue by lsiden** [thephpleague/flysystem-aws-s3-v3#88]
$fs->read(), $fs->has(), and $fs->getWithMetadata() all hang instead of returning null or throwing an exception as I would expect if I invoke any of them with a path that doesn't exist.  While we can avoid this use-case in our application, it would give me more confidence if methods return something (null) or throw an exception and not disappear into a black hole when asked to return a non-existent resource.

My coding partner and I did walked into the has() call with the debugger.  From what we could ascertain, a delegate creates a promise, but never rejects that promise if the file is not found, so the client is left waiting indefinitely for a promise that will never resolve or fail, until the request times out.

Here are some of our project's relevant dependencies and versions:

    league/flysystem                             1.0.32
    league/flysystem-aws-s3-v3          1.0.13

I am not familiar enough with the code to tell whether this may be a problem in flysystem and not flysystem-aws-s3-v3.  If the latter, I will repost this in that project.

Please advise if there is a latter version that fixes this.  I searched for "is:issue not found hang".

Thank you!

**Comment by frankdejonge** [comment]
@lsiden the actual code that could hang would be part of the official aws sdk, there's not really anything in Flysystem that could cause this, it's merely a wrapper/adapter.

**Comment by lsiden** [comment]
You are right.  My mistake.  Please close.

On Sat, Dec 17, 2016, 11:37 Frank de Jonge <notifications@github.com> wrote:

@lsiden <https://github.com/lsiden> the actual code that could hang would
be part of the official aws sdk, there's not really anything in Flysystem
that could cause this, it's merely a wrapper/adapter.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/flysystem-aws-s3-v3/issues/88#issuecomment-267772209>,
or mute the thread
