### ISSUE TITLE
Expires not setting

### ISSUE THREAD

**Issue by claygorman** [thephpleague/flysystem-aws-s3-v3#91]
I am not sure if I am not using expires correctly but here is my example... hoping someone could shed some light

When I go into s3 I see the file but no expiration is set.

```
$expires = '2016-01-06';

$s3client->put($filename, $data, ['visibility' => 'private', 'Expires' => gmdate('D, d M Y H:i:s T',$expires)]);

OR

$s3client->put($filename, $data, ['visibility' => 'private', 'Expires' => $expires]);
```

**Comment by claygorman** [comment]
I take it back.... It is setting but as metadata and not the actual object expiration (S3 auto removes this way)

I guess I misunderstand the Expires field?

**Comment by frankdejonge** [comment]
The `Expires` option is passed onto the SDK, I suggest opening an issue there to resolve this, from this end we can't fix this.
