### ISSUE TITLE
S3 too many requests

### ISSUE THREAD

**Issue by AidasK** [thephpleague/flysystem-aws-s3-v3#92]
More details:
https://github.com/thephpleague/flysystem/issues/744

Write and update methods are the same, so we don't need to check if file exists:
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L117
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L131

**Comment by franksl** [comment]
Hi,
delete() also should not call has()

**Comment by frankdejonge** [comment]
Closing this because the main repo fixed this problem.
