### ISSUE TITLE
Times out when laravel is running inside docker

### ISSUE THREAD

**Issue by Vishal0203** [thephpleague/flysystem-aws-s3-v3#94]
When my laravel application is running inside docker, the storage put command times out. It works well when I try running the application outside docker.

https://github.com/laravel/framework/issues/18185

here's the issue on laravel that I created but didn't get any response yet.

**Comment by frankdejonge** [comment]
Have you tried making a call with the aws sdk directly? Because it's probably a docker configuration/networking issue. Also, when you comment like that on open source issues, you come across as impatient. We're maintaining this in our spare time, you didn't even wait a day, nor does it seem you've tried a whole lot yourself to figure out what's going on.

**Comment by Vishal0203** [comment]
@frankdejonge I spent 2 days figuring out if it was an issue with S3 policies and or Amazon ECS security groups. Then I finally concluded it was happening only inside docker container. However, docker generally allows all outgoing requests. That made me raise an issue here. 
I'll try out aws sdk as you suggested.

**Comment by Vishal0203** [comment]
@frankdejonge okay, I tried boto to upload the file, and that works. i retried doing it using flysystem and that isn't working. 

Hangs at the same place.. 
<img width="938" alt="screen shot 2017-03-03 at 4 52 09 pm" src="https://cloud.githubusercontent.com/assets/8856973/23549343/cf2942a0-0031-11e7-974b-af03a33e29bb.png">

#### Using boto

```
import boto3

s3 = boto3.resource('s3')
s3.Bucket('bucket-name').put_object(Key='test.txt', Body='this is my content')
```

<img width="790" alt="2017-03-03_1655" src="https://cloud.githubusercontent.com/assets/8856973/23549453/5ac3d014-0032-11e7-91b6-1aec7e9aceeb.png">

**Comment by frankdejonge** [comment]
Could you try it using the aws sdk directly? Because it could be a
problem there.




Op Vr mrt 3 2017, om 12:26 schreef Vishal Sharma:

> @frankdejonge[1] okay, I tried boto to upload the file, and that
> works. i retried doing it using flysystem and that isn't working.
> Hangs at the same place.. screen shot 2017-03-03 at 4 5…



> Using boto


> import boto3  s3 = boto3.resource('s3') s3.Bucket('bucket-
> name').put_object(Key='test.txt', Body='this is my content')
>
> 2017-03-03_1655



> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/frankdejonge
  2. https://github.com/thephpleague/flysystem-aws-s3-v3/issues/94#issuecomment-283930991

**Comment by Vishal0203** [comment]
@frankdejonge 
I tried aws-php-sdk inside my docker and it works well i.e. I can see the file created in my s3. Here's the sample code 

```
<?php
// Include the SDK using the Composer autoloader
require 'vendor/autoload.php';

$s3 = new Aws\S3\S3Client([
    'version' => 'latest',
    'region'  => 'us-east-1'
]);

$result = $s3->putObject([
    'Bucket' => 'bucket-name',
    'Key'    => 'test.txt',
    'Body'   => 'this is the body!'
]);

echo $result['Body'];
```

**Comment by frankdejonge** [comment]
Do you use the same upload method as you do with using flysystem? As in is that also using a write, not a write stream?

**Comment by Vishal0203** [comment]
I'm not using flysystem methods directly as you can see in the sample image I uploaded. Laravel docs suggests to use flysystem and provides a few minimal configs. Hence, the method I use is just `Storage::put()` haven't really seen what they do internally. 

I felt it was because of config cache before, but my application is able to read configs. I'll try reading  laravel's source and answer you. 

For now, I replaced the usage of flysystem and laravel's storage with aws-sdk impl, and things are working fine.

**Comment by Vishal0203** [comment]
@frankdejonge Okay, I took a look at laravel's code. I think they are using write stream. Here's the piece of code.

```
/**
     * Write the contents of a file.
     *
     * @param  string  $path
     * @param  string|resource  $contents
     * @param  array  $options
     * @return bool
     */
    public function put($path, $contents, $options = [])
    {
        if (is_string($options)) {
            $options = ['visibility' => $options];
        }
        // If the given contents is actually a file or uploaded file instance than we will
        // automatically store the file using a stream. This provides a convenient path
        // for the developer to store streams without managing them manually in code.
        if ($contents instanceof File ||
            $contents instanceof UploadedFile) {
            return $this->putFile($path, $contents, $options);
        }
        return is_resource($contents)
                ? $this->driver->putStream($path, $contents, $options)
                : $this->driver->put($path, $contents, $options);
    }
```

[This line on their git repo](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Filesystem/FilesystemAdapter.php#L103)

**Comment by vingrad** [comment]
Do you have find the solution?

**Comment by Vishal0203** [comment]
@vingrad nope, couldn't get it working with flysystem. I used this library instead: https://github.com/aws/aws-sdk-php-laravel 

And this works perfectly.

**Comment by BorjaRafols** [comment]
For those of you that find this post. You might solve this issue by reading this:
https://serverfault.com/questions/642981/docker-containers-cant-resolve-dns-on-ubuntu-14-04-desktop-host

It has nothing to do with this package nor with Laravel.
