### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by mcblum** [thephpleague/flysystem-aws-s3-v3#97]
Hello - for whatever reason any time I try to install this composer just hangs forever. I've tried self-updated, removing the cache, removing /vendor, all the stuff you would think. It just hangs and hangs and never installs. Any ideas?

**Comment by frankdejonge** [comment]
No clue, seems more like a composer network issue. With this information I can't really help you either, sorry.

**Comment by frankdejonge** [comment]
Closing because there's nothing I can do about this.
