### ISSUE TITLE
Error font when upload file include utf8 string to aws s3

### ISSUE THREAD

**Issue by vominhtam** [thephpleague/flysystem-aws-s3-v3#98]
Hi all, 
I have a file csv include string utf8. I read content file and base64_encode it.  then upload to aws when download file I see font display incorrect. 

 "Báº¯n Vá»‹"

Please help me resolve it thank all so much

**Comment by frankdejonge** [comment]
@vominhtam you don't need to base64_encode it. Just upload the file like it is in order to get the right output.
