### ISSUE TITLE
InvalidArgumentException in ClientResolver.php line 364: Missing required client configuration options: 

### ISSUE THREAD

**Issue by sagarshah16** [thephpleague/flysystem-aws-s3-v3#99]
hell guys, 
 I am trying to setup amazon s3 with larval 5.4
  so far I have made  changes 

1) composer.json 
"league/flysystem-aws-s3-v3": "^1.0",
2_ .env
AWS_KEY= key
 AWS_SECRET= secret
AWS_REGION= region
AWS_BUCKET= bucket name

3)  web.php
Route::get('/', 'UploadBillController@load');  Route::post('/upload-bill', 'UploadBillController@fileUpload');
4)  controller. 

<?php
namespace App\Http\Controllers;
use App\Image;
use Illuminate\Http\Request;
use Illuminate\Contracts\Filesystem\Filesystem;
use Illuminate\Support\Facades\Storage;
ini_set('max_execution_time', 300);
class UploadBillController extends Controller
{
    public function load() {
        $images = Image::where('user', 'example')->get();
        return view('/employee/upload-bill', ['images' => $images]);
    }
    public function fileUpload(Request $request)
    {
        /*$this->validate($request, [
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);*/
        $imageName = time().'.'.$request->image->getClientOriginalExtension();
        $image = $request->file('image');
        $t = Storage::disk('s3')->put($imageName, file_get_contents($image), 'public');
        $imageName = Storage::disk('s3')->url($imageName);
        $path = explode("/", $imageName);
        $path = end($path);
        $image = Image::create(['user' => 'example', 'path' => $path]);
        return back();
    }
}
 
but I am getting  errors saying 

InvalidArgumentException in ClientResolver.php line 364:
Missing required client configuration options: 
1. in ClientResolver.php line 364
2. at ClientResolver->throwRequired(array('driver' => 's3', 'key' => null, 'secret' => null, 'region' => null, 'bucket' => null, 'version' => 'latest', 'service' => 's3', 'exception_class' => 'Aws\\S3\\Exception\\S3Exception', 'config' => array(), 'scheme' => 'https')) in ClientResolver.php line 260
3. at ClientResolver->resolve(array('driver' => 's3', 'key' => null, 'secret' => null, 'region' => null, 'bucket' => null, 'version' => 'latest', 'service' => 's3', 'exception_class' => 'Aws\\S3\\Exception\\S3Exception', 'config' => array(), 'scheme' => 'https'), object(HandlerList)) in AwsClient.php line 158
4. at AwsClient->__construct(array('driver' => 's3', 'key' => null, 'secret' => null, 'region' => null, 'bucket' => null, 'version' => 'latest', 'service' => 's3', 'exception_class' => 'Aws\\S3\\Exception\\S3Exception')) in S3Client.php line 243
5. at S3Client->__construct(array('driver' => 's3', 'key' => null, 'secret' => null, 'region' => null, 'bucket' => null, 'version' => 'latest')) in FilesystemManager.php line 193
6. at FilesystemManager->createS3Driver(array('driver' => 's3', 'key' => null, 'secret' => null, 'region' => null, 'bucket' => null)) in FilesystemManager.php line 119
7. at FilesystemManager->resolve('s3') in FilesystemManager.php line 97
8. at FilesystemManager->get('s3') in FilesystemManager.php line 74
9. at FilesystemManager->disk('s3') in Facade.php line 221
10. at Facade::__callStatic('disk', array('s3')) in UploadBillController.php line 31
11. at UploadBillController->fileUpload(object(Request))
12. at call_user_func_array(array(object(UploadBillController), 'fileUpload'), array(object(Request))) in Controller.php line 55
13. at Controller->callAction('fileUpload', array(object(Request))) in ControllerDispatcher.php line 44
14. at ControllerDispatcher->dispatch(object(Route), object(UploadBillController), 'fileUpload') in Route.php line 203
15. at Route->runController() in Route.php line 160
16. at Route->run() in Router.php line 559
17. at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 30
18. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
19. at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 148
20. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
21. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
22. at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
23. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
24. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
25. at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
26. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
27. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
28. at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
29. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
30. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
31. at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 148
32. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
33. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
34. at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 148
35. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
36. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
37. at Pipeline->then(object(Closure)) in Router.php line 561
38. at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
39. at Router->dispatchToRoute(object(Request)) in Router.php line 498
40. at Router->dispatch(object(Request)) in Kernel.php line 174
41. at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
42. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
43. at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
44. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
45. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
46. at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
47. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
48. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ValidatePostSize.php line 27
49. at ValidatePostSize->handle(object(Request), object(Closure)) in Pipeline.php line 148
50. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
51. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
52. at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
53. at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
54. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
55. at Pipeline->then(object(Closure)) in Kernel.php line 149
56. at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
57. at Kernel->handle(object(Request)) in index.php line 53

**Comment by frankdejonge** [comment]
This is not an issue with flysystem.
